### ISSUE TITLE
Certificate Request Form (CRF) Worksheet Guide

### ISSUE THREAD

**Issue by MattKing1** [GSA/fpki-guides#10]
This playbook provides guidance to Affiliates on how to complete the [Certificate Request Form](https://www.idmanagement.gov/IDM/s/document_detail?Id=kA0t00000008OciCAE) when requesting a new certificate from the FPKI

**Comment by lachellel** [comment]
how many people does this cover?  it's a pretty small population that does this, correct?

@djpackham let's start defining labels to track Audience?  I want to ensure we don't confuse the agency engineers, who request certificates from the subordinate CAs and not from FPKI.

**Comment by djpackham** [comment]
Yes, sounds like a fine idea. We'll go ahead and add Audience labels to the different plays.
