### ISSUE TITLE
Consistency of Template.md pages

### ISSUE THREAD

**Issue by clstmbrly** [GSA/fpki-guides#108]
#### Description of Issue: ####
The content contained in the Template.md pages (and their locations in the directory structures) is not consistent across the FPKI-Guides, PIV-Guides, and FICAM-Arch repos.

#### Details of Issue: ####
1.	The Template.md pages provide style and general instructions for those who need to write guides or information for the FPKI-Guides, PIV-Guides, and FICAM-Arch. 
2.	The content contained in the Template.md pages is not consistent across the 3 repos.  
3.	The Template.md pages are not located at the same directory structure level for all 3 repos. 

#### References (Docs, Links, Files): ####
https://github.com/GSA/fpki-guides/blob/staging/template.md
https://github.com/GSA/fpki-guides/blob/staging/pages/template.md
https://github.com/GSA/piv-guides/blob/staging/pages/template.md
https://github.com/GSA/ficam-arch/blob/staging/template.md

#### If a New Page or Content is Needed, Expected Outcomes: ####
1.	Make the content consistent for all Template.md pages:  sample outline for guides, the same style and general instructions, and Markdown syntax (style sheet).
2.	Place all Template.md pages in a consistent location in the directory structures for all 3 repos.

#### Link to the Content Page for Contributors: ####
None.

**Comment by clstmbrly** [comment]
Will replicate these PIV-Guides files to FPKI-Guides:
- template.md
- contribute.md 
- contribute_addpage.md
- contribute_editpage.md
- contribute_openissue.md

**Note:**  Encountering some broken links within PIV-Guides files that I will need to resolve before replicating.

**Comment by lachellel** [comment]
closing
merged in #116 
thank you
