### ISSUE TITLE
Annual PIV Card Issuer (PCI) Testing Guide

### ISSUE THREAD

**Issue by MattKing1** [GSA/fpki-guides#11]
This playbook provides guidance to PIV Card Issuers on how to complete [annual Card Testing](https://www.idmanagement.gov/IDM/s/document_detail?Id=kA0t00000008ObNCAU)

**Comment by dasgituser** [comment]
This playbook will provide PIV Providers with step-by-step instructions and requirements to demonstrate initial and annual PIV Card conformance to NIST requirements and technical interoperation with elements of the Federal PIV infrastructure. This will help PIV Providers better understand and prepare for the testing, which in turn should result in more on-time, efficient, and effective testing.

**Comment by lachellel** [comment]
closed...small audience...moved to idmanagement.gov
