### ISSUE TITLE
update Federalist banners for Internal Reference alignment

### ISSUE THREAD

**Issue by Protiviti-JSargent** [GSA/fpki-guides#119]
#### Description of Issue: ####
When clicking on any of the internal reference links on a page, the section header and the first 3-4 lines of content are covered/hidden by the federalist page banner.

#### Details of Issue: ####
It may be possible to modify the css script to account for the banner width.  Otherwise, modifying each of the pages individually to adjust the header links will be clunky and time consuming and may not be worth the effort at this time.

#### References (Docs, Links, Files): ####
example of the issue:  https://fpki.idmanagement.gov/#what-is-an-example

**Comment by lachellel** [comment]
Cross reference with: https://github.com/GSA/piv-guides/issues/110

**Comment by lachellel** [comment]
Just fyi - it's the **top navigation bar** (links to idmanagement, piv, fpki, architecture) that caused this.

**Comment by lachellel** [comment]
quick look at this again - and need to verify and test - but an option might be: 

- moving the navbar to the head versus the body, for where it's loaded in the default layout
- https://github.com/GSA/fpki-guides/blob/staging/_layouts/default.html#L10

**Comment by idmken** [comment]
This was addressed with new header navbar.
