### ISSUE TITLE
Agency C&A of SSPs Guidance

### ISSUE THREAD

**Issue by MattKing1** [GSA/fpki-guides#12]
This playbook provides guidance to agencies on [how to leverage the C&A](https://www.idmanagement.gov/IDM/servlet/fileField?entityId=ka0t0000000TNSGAA4&field=File__Body__s) conducted by GSA when the agency completes its FISMA assessment of the agency's SSP

**Comment by ryancdickson** [comment]
Are we comfortable closing this issue?

**Comment by idmken** [comment]
The referenced document no longer exists and this is address in the SSP guide revision.
