### ISSUE TITLE
Certificate Policies Table

### ISSUE THREAD

**Issue by mttcpr** [GSA/fpki-guides#125]
#### Description of Issue: ####
"Risk" column heading is confusing. 

#### Details of Issue: ####
It seems to state that "common-high" is "High risk"? I think it would be better to split that column into two columns - Maybe "Security Level" or "Assurance Level" (e.g. High, Medium) and "Purpose" or "Description"

#### Link to the Content Page for Contributors: ####
https://github.com/GSA/fpki-guides/blob/staging/pages/fpki_certificate_policies.md

**Comment by lachellel** [comment]
Agree - that page isn't published yet.  It's genesis was #18 and https://www.idmanagement.gov/wp-content/uploads/sites/1171/uploads/FPKI-Trust-InfrastructureOverview.pdf

An attempt to take the all the sections of that document that wasn't very clear "who the audience was" and break it down, adopt plain language, focus on audience and expected outcomes (etc).   Most of the up-front sections were mapped already.  

Section 5 + 6 + 7 were the open items.   What are we trying to say?  Who is the audience?

**Comment by weirdscience** [comment]
Section 5
Audience: Federal relying parties
Purpose: Help relying parties understand which FPKI certificate is either a person or device certificate. If they are doing policy validation, helps them ensure they are accepting the correct certificate.
Fix: Agree - risk level is not defined so we should remove it and plain language the certificate purpose.

Section 6
Audience: Federal relying party
Purpose: Align FPKI certificates with M04-04 and NIST 800-63-3 LOAs. 
Fix: With the new 63-3, this table should be updated.

Section 7:
Audience: Engineers
Purpose: Explain how certificate policies map back to COMMON and show how FBCA certificates have comparability with COMMON.
Fix: ?

**Comment by idmken** [comment]
This is a subset of issue #18
