### ISSUE TITLE
FPKI Graph - Revise the content with context

### ISSUE THREAD

**Issue by indrajit-gsa** [GSA/fpki-guides#135]
#### Description of Issue: ####
Breakup the FPKI Crawler to separate the FPKI Graph from the Crawler.

#### Details of Issue: ####
This issue will revise the FPKI Crawler playbook and break it down into a separate playbook about the FPKI Graph.

**Comment by indrajit-gsa** [comment]
@lachellel @clstmbrly 

I updated the text for the FPKI Graph with some additional information related to AIA and SIA linking. Do we need any further information on the Federal Bridge or SSP?

https://github.com/GSA/fpki-guides/blob/indrajit-gsa-fpki-crawler/_tools/01_fpki_graph.md

**Comment by clstmbrly** [comment]
@indrajit-gsa @lachellel Should I proceed with editorial review of these revisions/new material?  Thank you.

**Comment by clstmbrly** [comment]
@lachellel @indrajit-gsa For someone who is coming to the FPKI Graph to just see a visual representation of CA relationships, isn't the AIA and SIA extension information = too much information?  Isn't it more likely that those who come to the FPKI Crawler may want/need to understand how the AIA and SIA extensions are used?

**Comment by lachellel** [comment]
i just updated the content.  moved the aia and sia descriptions to a "how this works" section at the bottom.   Does this work better?  Feel free to edit and get it published!

**Comment by clstmbrly** [comment]
@lachellel Thank you!  I'll go take a look:-)

**Comment by clstmbrly** [comment]
@lachellel Re:  this sentence: "Each **_ring_** represents *one* certificate in a chain from COMMON"-- should "Each **_ring_** really be "Each _dot_**"?

**Comment by clstmbrly** [comment]
Or rather, each link between dots represents one certificate?

**Comment by lachellel** [comment]
or just remove it...

**Comment by clstmbrly** [comment]
@lachellel To respond to your earlier question--yes, the "how it works" section for AIA and SIA discussion works much better.  Thanks!
