### ISSUE TITLE
System Notification for: Federal PKI Trust Infrastructure

### ISSUE THREAD

**Issue by weirdscience** [GSA/fpki-guides#137]
notice_date: September 30, 2017
change_type:  CA Certificate Issuance 
start_datetime: ‎Thursday, ‎September ‎28, ‎2017 11:52:49
end_datetime: ‎Monday, ‎September ‎28, ‎2020 11:52:36
system: Federal PKI Trust Infrastructure
change_description: Issuance of cross-certificate from Federal Bridge to DigiCert
contact: FPKI@GSA.gov
ca_certificate_hash: e8 0b dd c6 1e d8 c4 3a d0 95 fc 94 62 17 be 45 bd d3 47 c1
ca_certificate_issuer: Federal Bridge CA 2016
ca_certificate_subject: DigiCert Federated ID CA-1
cdp_uri: http://http.fpki.gov/bridge/fbca2016.crl
aia_uri: http://http.fpki.gov/bridge/caCertsIssuedTofbca2016.p7c
sia_uri: http://cacerts.digicert.com/siaDigiCertFederatedIDCA-1.p7c
ocsp_uri: N/A

**Comment by lachellel** [comment]
closed by #139
