### ISSUE TITLE
PIV-I Testing Guide

### ISSUE THREAD

**Issue by MattKing1** [GSA/fpki-guides#14]
This playbook provides guidance to PIV-I providers for [testing of PIV-I credentials](https://www.idmanagement.gov/IDM/servlet/fileField?entityId=ka0t0000000TNHSAA4&field=File__Body__s)

**Comment by dasgituser** [comment]
This playbook will provide PIV-I Providers with step-by-step instructions and requirements to demonstrate initial and annual PIV-I Card conformance to FPKI  policy requirements and technical interoperation with elements of the Federal smart  card infrastructure. This will help PIV-I Providers better understand and prepare for the testing, which in turn should result in more on-time, efficient, and effective testing.

**Comment by idmken** [comment]
Document no longer exists
