### ISSUE TITLE
Certificate Profile - Merge and Migrate Documents to Playbook

### ISSUE THREAD

**Issue by indrajit-gsa** [GSA/fpki-guides#145]
#### Description of Issue: ####
The certificate profile documents in the fpki guide on the idmanagement.gov website will require merging and transformation to playbooks for simpler search and navigation.

#### Details of Issue: ####
There are multiple certificate profile documents for SSP, bridge and PIV-i which will require consolidation of content and then splitting the worksheets into navigable playbook content.

#### References (Docs, Links, Files): ####
The following 3 documents will be evaluated for this issue.
https://www.idmanagement.gov/wp-content/uploads/sites/1171/uploads/fpki-cert-profile-ssp.pdf
https://www.idmanagement.gov/wp-content/uploads/sites/1171/uploads/fpki-x509-cert-profiles.pdf
https://www.idmanagement.gov/wp-content/uploads/sites/1171/uploads/fpki-pivi-cert-profiles.pdf

#### Link to the Content Page for Contributors: ####
This issue will cover the materials under the Certificate Profiles section of the fpki guide found at this link.
https://www.idmanagement.gov/fpki/

**Comment by lachellel** [comment]
Let's consider using the devicepki (github.com/uspki/policies & devicepki.idmanagement.gov) markdown for the devicepki certificate profiles as a template.  We have a different navigation but the markdown formats can be similar and reusable.

**Comment by lachellel** [comment]
**Proposed order and navigation:**

- Reorder the worksheets (numbering) - currently, the numbers flip between the policies.  For example, a Federal Bridge profile for end entity signature is numbered before the common profile for end entity signature.  But in another set (auth profiles), it's common (piv, derived) then fed bridge (piv-i).

- Draft up a consolidation of tables / worksheets that shows all of similar usage and type:
  
1.  **PIV Auth, PIV-I Auth, Derived PIV (auth)**
2.  PIV Card Auth, PIV-I Card Auth
3.  PIV Key Management, PIV-I Key Management, FBCA Key Management
4.  **_End Entity_ Signature / PIV, PIV-I Dig Sig, FBCA End Entity Signature**
4.  PIV Content Signing, PIV-I Content Signing
4.  CA Certificates (all four)
4.  Devices - and add explanation
4.  CRL 
4. OCSP

- Use column to show differences in the Extensions by policy / type.  
- Add explanatory information INTO each profile markdown using an introduction and bullets
- Question: why do we call out End Entity in some of the profiles and not others (that are end entity)

**Comment by clstmbrly** [comment]
@lachellel @djpackham @indrajit-gsa   Please take a look at the combined PIV, PIV-I, and Derived PIV Authentication cert profile at https://github.com/GSA/fpki-guides/blob/145-cert-profiles-migrate/_profiles/21_all_piv-auth.md. 

The extension values make for long, narrow columns in some cases.  For the Subject Directory Attributes extension, I shortened the verbiage by saying:  "Same as for PIV Authentication," which could be done in a few other cases (although it will not necessarily shorten the columns).  

A top-align function in Markdown would help the display, but it doesn't seem to exist. 

Please let me know your thoughts.  This is just a test.

**Comment by clstmbrly** [comment]
@lachellel @djpackham @indrajit-gsa I've updated the combined PIV, Derived PIV, and PIV-I Authentication Profile, per recent suggestions and comments.  Added a small traceability table (will do this for each profile, if it works) as a way to eventually remove the larger, *confusing* matrix on the landing page.  Removed the Mandatory and Optional Column and split Extensions into 2 tables:  Mandatory and Optional.  Add "Source" link row to Extensions table to link to previous CPs.  Reduced words related to Section 7 extracted text.  Tried to improve titling/formatting, wording, and overall flow with the sections we have now.

[https://github.com/GSA/fpki-guides/blob/145-cert-profiles-migrate/_profiles/21_all_piv_auth.md](url)

Would appreciate your further thoughts and suggestions.

Have a great weekend.

**Comment by clstmbrly** [comment]
@lachellel @djpackham @indrajit-gsa The latest version of the combined PIV, Derived PIV, and PIV-I Authentication Cert Profile is ready for your review.  I've incorporated content changes from Wendy; made structural changes based on Wendy's and Jordan's inputs; and did additional formatting, wordsmithing, etc.  Looks good in Federalist Live Preview.

Please let me know if you have additional suggestions or changes.

[https://github.com/GSA/fpki-guides/blob/145-cert-profiles-migrate/_profiles/23_all_piv_auth.md](url)

Enjoy your time off.  Happy Holidays!

**Comment by techliaison** [comment]
PIV Classes  is not a good header when you are including PIV-I which is not a PIV – besides what is a class?  Do you mean certificates?

Subject AltName – again the majority of the text should be consistent across the row and I really think this table would still be better without having 3 separate columns
If you are going to include this text for UUI – it belongs in all 3 “encoded as a URI, as specified in RFC 4122,8<https://github.com/GSA/fpki-guides/blob/145-cert-profiles-migrate/_profiles/23_all_piv_auth.md#8> Section 3.”
These 2 sentences are redundant with each other – pick one or the other – and again is common across all coumns

The description of PIV Interim is way to big when only 1/3rd of the width this row ends up taking up an entire screen all by itself

Again – this description is repetitive – only list the EKU names once and not under “additional key purposes”  And what is the last sentence meant to mean?
If included to support specific applications, this extension should be non-critical. The following values for keyPurposeID should be included:
Microsoft Smart Card Logon; however, if the private key is not on a smart card, do not include the EKU for Microsoft Smart Card Logon.
TLS Client Authentication
pkinit-KPClientAuth
Additional key purposes may be specified:
TLS Client Authentication {3.6.1.5.5.7.3.2}
id-pkinit-KPClientAuth {3.6.1.5.2.3.4}
id-kp-secureShellClient {3.6.1.5.5.7.3.21}
The keyPurposeID value may be implemented as needed by the subscriber.

You are missing a carriage return before footnote 3

**Comment by indrajit-gsa** [comment]
Here is the 'preview link' for the certificate profiles as we progress through the feedback process. It will be easier to view the details of each certificate profile. 

https://federalist-proxy.app.cloud.gov/preview/gsa/fpki-guides/145-cert-profiles-migrate/certprofiles/

**Comment by clstmbrly** [comment]
@techliaison I will email you to get clarification about some of your inputs.  Thanks!

**Comment by clstmbrly** [comment]
@lachellel @djpackham The updated PIV, D-PIV, and PIV-I Authentication cert profile is available for your review.  All of Wendy's changes have been addressed, plus editorial and formatting.  Some changes were made to try to shorten the profile length.  Would appreciate any feedback.  Thanks!

[https://github.com/GSA/fpki-guides/blob/145-cert-profiles-migrate/_profiles/23_all_piv_auth.md]

**Comment by ryancdickson** [comment]
@idmken - given recent updates to the profile formatting for V2.0 - we could easily take the contents and convert into markdown.  Would you like us move forward with this (for at least the Common Policy profiles)?

**Comment by maxwellfunk** [comment]
Closing as we plan on migrating the pdf formats of the documents into the new repo
