### ISSUE TITLE
System Notification for: ORC (Widepoint) ACES 4

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#150]
notice_date:  November 16, 2017
change_type:  CA Certificate Issuance
start_datetime: August 21, 2017
system: Federal PKI Trust Infrastructure
change_description: Issuance of cross-certificate from Federal Bridge to ORC (Widepoint) ACES
contact: fpki@gsa.gov
ca_certificate_hash: 55 73 fc c5 e6 ff ff 2b 71 01 81 ac ca a2 ef da db 8f 0f 4e
ca_certificate_issuer: Federal Bridge CA 2016
ca_certificate_subject:  CN=ORC ACES 4, O=ORC PKI, C=US
cdp_uri: http://http.fpki.gov/bridge/fbca2016.crl
aia_uri: http://http.fpki.gov/bridge/caCertsIssuedTofbca2016.p7c
sia_uri: http://crl-server.orc.com/caCerts/ORCACES4_SIA.p7c

**Comment by indrajit-gsa** [comment]
Pull request #156 submitted for this issue.
https://github.com/GSA/fpki-guides/pull/156
