### ISSUE TITLE
System Notification for: ORC (Widepoint) Non-Federal Issuer CA

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#151]
notice_date: November 16, 2017
change_type:  CA Certificate Issuance
start_datetime: October 4, 2017
system: Federal PKI Trust Infrastructure
change_description: Issuance of cross-certificate from Federal Bridge to ORC (Widepoint) Non-Federal Issuer CA
contact: fpki@gsa.gov
ca_certificate_hash: b0 55 c6 ee 10 4e 01 eb 68 8c 8f b4 f8 7c f7 7c a3 76 af db
ca_certificate_issuer: Federal Bridge CA 2016
ca_certificate_subject: CN=ORC NFI CA 2, O=ORC PKI, C=US
cdp_uri: http://http.fpki.gov/bridge/fbca2016.crl
aia_uri: http://http.fpki.gov/bridge/caCertsIssuedTofbca2016.p7c
sia_uri: http://crl-server.orc.com/caCerts/ORCNFI2_SIA.p7c

**Comment by indrajit-gsa** [comment]
Pull request #156 submitted for this issue.
