### ISSUE TITLE
System Notification for: Symantec 

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#152]
notice_date:  November 16, 2017
change_type:  CA Certificate Issuance 
start_datetime: October 25, 2017
system: Federal PKI Trust Infrastructure
change_description:  Issuance of cross-certificate from Federal Bridge to Symantec 
contact: fpki@gsa.gov
ca_certificate_hash: 91 45 31 f5 a6 10 91 40 05 42 2e 56 d6 71 12 18 13 3b 10 48
ca_certificate_issuer: Federal Bridge CA 2016
ca_certificate_subject: CN=Symantec Class 3 SSP Intermediate CA - G3
cdp_uri: http://http.fpki.gov/bridge/fbca2016.crl
aia_uri: http://http.fpki.gov/bridge/caCertsIssuedTofbca2016.p7c
sia_uri: http://ssp-sia.symauth.com/STNSSP/Certs_Issued_by_Class3SSPCA-G3.p7c

**Comment by indrajit-gsa** [comment]
Pull request #156 submitted for this issue.
https://github.com/GSA/fpki-guides/pull/156
