### ISSUE TITLE
System Notification for: Verizon

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#153]
notice_date: November 16, 2017
change_type:  CA Certificate Issuance, CA Certificate Revocation, New CA, URI Change, System Outage 
start_datetime: October 4, 2017
system: Federal PKI Trust Infrastructure
change_description: Issuance of cross-certificate from Federal Bridge to Verizon Non-Federal Issuer CA
contact: fpki@gsa.gov
ca_certificate_hash: 68 70 66 bc e5 6b 6e 20 ae a0 c6 05 b9 b6 67 93 42 26 9f 21
ca_certificate_issuer: Federal Bridge CA 2016
ca_certificate_subject: CT-CSSP-CA-A1
cdp_uri: http://http.fpki.gov/bridge/fbca2016.crl
aia_uri: http://http.fpki.gov/bridge/caCertsIssuedTofbca2016.p7c
sia_uri: http://sia1.com-strong-id.net/CA/CT-CSSP-CA-A1-SIA.p7c

**Comment by indrajit-gsa** [comment]
Pull request #156 submitted for this issue.
https://github.com/GSA/fpki-guides/pull/156
