### ISSUE TITLE
System Notification for: Entrust Non-Federal 

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#154]
notice_date: November 16, 2017
change_type:  CA Certificate Issuance 
start_datetime:  November 20, 2017
system: Federal PKI Trust Infrastructure
change_description: Issuance of cross-certificate from Federal Bridge to Entrust Non-Federal
contact: fpki@gsa.gov
ca_certificate_issuer: Federal Bridge CA 2016
ca_certificate_subject: Entrust Managed Services NFI Root CA

**Comment by techliaison** [comment]
change description should say Entrust not Symantec

**Comment by lachellel** [comment]
:+1:  thanks!  (copy / paste and forgot to modify)
