### ISSUE TITLE
System Notification for: Federal PKI Trust Infrastructure

### ISSUE THREAD

**Issue by weirdscience** [GSA/fpki-guides#155]
notice_date: Nov 17, 2017
change_type:  CA Certificate Issuance
start_datetime: ‎Thursday, ‎November ‎16, ‎2017 14:52:56
end_datetime: ‎Monday, ‎November ‎16, ‎2020 14:52:26
system: Federal Bridge CA 2016
change_description: CA certificate renewal to the Entrust NFI Root CA
contact: FPKI@gsa.gov
ca_certificate_hash: ‎22 05 08 b0 ab 72 e2 ee 3a ca a6 a9 ef 50 01 c8 7c 52 3e a4
ca_certificate_issuer: CN = Federal Bridge CA 2016, OU = FPKI, O = U.S. Government, C = US
ca_certificate_subject: OU = Entrust Managed Services NFI Root CA, OU = Certification Authorities, O = Entrust, C = US
cdp_uri: http://http.fpki.gov/bridge/fbca2016.crl
aia_uri: http://http.fpki.gov/bridge/caCertsIssuedTofbca2016.p7c
sia_uri: http://nfirootweb.managed.entrust.com/SIA/CAcertsIssuedByNFIRootCA.p7c, ldap://nfirootdir.managed.entrust.com/ou=Entrust Managed Services NFI Root CA,ou=Certification Authorities,o=Entrust,c=US?crossCertificatePair;binary 
ocsp_uri: N/A

**Comment by lachellel** [comment]
dup with #154.  I'll close #154.

**Comment by lachellel** [comment]
Updated to merge #154

notice_date: November 16, 2017
change_type: CA Certificate Issuance
start_datetime: ‎Thursday, ‎November ‎16, ‎2017 14:52:56
system: Federal PKI Trust Infrastructure
change_description: Issuance of cross-certificate from Federal Bridge 2016 to Entrust Non-Federal Root CA
contact: fpki@gsa.gov
ca_certificate_hash: ‎22 05 08 b0 ab 72 e2 ee 3a ca a6 a9 ef 50 01 c8 7c 52 3e a4
ca_certificate_issuer: CN = Federal Bridge CA 2016, OU = FPKI, O = U.S. Government, C = US
ca_certificate_subject: OU = Entrust Managed Services NFI Root CA, OU = Certification Authorities, O = Entrust, C = US
cdp_uri: http://http.fpki.gov/bridge/fbca2016.crl
aia_uri: http://http.fpki.gov/bridge/caCertsIssuedTofbca2016.p7c
sia_uri: http://nfirootweb.managed.entrust.com/SIA/CAcertsIssuedByNFIRootCA.p7c

**Comment by indrajit-gsa** [comment]
Pull request #156 submitted for this issue.
https://github.com/GSA/fpki-guides/pull/156
