### ISSUE TITLE
Distinguishing between certs on a PIV

### ISSUE THREAD

**Issue by woodyweaver** [GSA/fpki-guides#159]
#### Description of Issue: ####

Users (and engineers) often don't understand the differences between the auth and digital signature cert.  It would be helpful to expand on the explanation from a functional and programmatic perspective.

#### Details of Issue: ####

A useful application would be to force use of the auth cert rather than the digital signature cert when performing client authentication (e.g. SSL client auth.)  For a PIV, this can be achieved by checking for 2.16.840.1.101.3.2.1.3.13.  However, if the application needs to interoperate with the DoD environment, this OID may or may not be present (it looks like the DoD SHA2 CAC asserts the Common Auth OID, but others don't.)

Recommendations on how to achieve that distinction programmatically across the entirety of the Federal bridge would be welcome.

**Comment by clstmbrly** [comment]
Combining FPKI-Guides' Issue #159 with PIV-Guides' #101 due to similar request.  PIV-Guides is a more applicable location.  Closing FPKI-Guides' #159.
