### ISSUE TITLE
FPKI and FBCA Overview

### ISSUE THREAD

**Issue by MattKing1** [GSA/fpki-guides#16]
This playbook provides an overview of the historical purpose and plan for [the FPKI and FBCA](https://www.idmanagement.gov/IDM/servlet/fileField?entityId=ka0t0000000TN8uAAG&field=File__Body__s)

**Comment by dasgituser** [comment]
After discussion with Jordan, this playbook is being rolled into the FPKI Trust Infrastructure Overview playbook (issue #18) since it is essentially a sub topic within that broader overview playbook.  Therefore, this issue should be considered No Action / Closed.
