### ISSUE TITLE
System Notification for: NextgenID cross certificate for CertiPath Bridge CA - G2

### ISSUE THREAD

**Issue by indrajit-gsa** [GSA/fpki-guides#163]
notice_date: January 2, 2018
change_type:  CA Certificate Issuance
start_datetime: TBD
end_datetime: NA
system: CertiPath Bridge
change_description: CertiPath Policy Management Authority has approved NextgenID for cross certification with the CertiPath Bridge CA – G2 for the following certificate types:

CertiPath Assurance Level | NextgenID Assurance Level
-- | --
Medium Software {1.3.6.1.4.1.24019.1.1.1.1} | id-mediumSoftware {1.3.6.1.4.1.49758.1.1.1.3}
Medium Hardware {1.3.6.1.4.1.24019.1.1.1.2} | id-mediumHardware {1.3.6.1.4.1.49758.1.1.1.4}
Medium Software CBP {1.3.6.1.4.1.24019.1.1.1.4} | id-mediumCBPSoftware {1.3.6.1.4.1.49758.1.1.1.5}
Medium Hardware CBP {1.3.6.1.4.1.24019.1.1.1.5} | id-mediumCBPHardware {1.3.6.1.4.1.49758.1.1.1.6}
IceCAP Hardware {1.3.6.1.4.1.24019.1.1.1.7} | id-IceCAP-hardware {1.3.6.1.4.1.49758.1.1.1.7}
IceCAP Card Authentication {1.3.6.1.4.1.24019.1.1.1.8} | id-IceCAP-cardAuth {1.3.6.1.4.1.49758.1.1.1.8}
IceCAP Content Signing {1.3.6.1.4.1.24019.1.1.1.9} | Id-IceCAP-contentSigning {1.3.6.1.4.1.49758.1.1.1.9}

contact: fpki@gsa.gov
ca_certificate_hash: 
ca_certificate_issuer: CertiPath Bridge CA - G2
ca_certificate_subject: 
cdp_uri: 
aia_uri: 
sia_uri: 
ocsp_uri:

**Comment by indrajit-gsa** [comment]
The cross certificate will be issued later in January 2018.

**Comment by lachellel** [comment]
~~system: Federal PKI Trust Infrastructure~~

system: CertiPath Bridge

**Comment by indrajit-gsa** [comment]
@lachellel Submitted pull request #164.

**Comment by lachellel** [comment]
#165

**Comment by indrajit-gsa** [comment]
Updating with issuance information.

Notice date: January 2, 2018
System: CertiPath Bridge
Type: CA Certificate Issuance
Start Date and Time: Monday, ‎January ‎22, ‎2018 7:00:00 PM
End Date and Time: ‎Thursday, ‎February ‎28, ‎2019 6:59:59 PM
Change Description: CertiPath has approved NextgenID for cross certification with the CertiPath Bridge CA – G2. The cross certificate will be issued later in January 2018.
Contact: fpki@gsa.gov
Certificate Issuer: CN = CertiPath Bridge CA - G2, OU = Certification Authorities, O = CertiPath LLC, C = US
Certificate Subject: CN = NextgenIDRootCA1, OU = Certification Authorities, O = NextgenID, C = US
Certificate SHA1 HASH: 50a2bf7afe08edf3877854f6d0a6e59127f68a94
Serial:  ‎70 6d 34 64 b2 00 c2 b3 75 2e 03 62 b3 d4 5d 23
Certificate Revocation List: http://certipath-crl.symauth.com/CertiPathBridgeCA-G2.crl
Certificate Bundle (AIA): http://certipath-aia.symauth.com/CertiPathBridgeCA-G2.p7c
Certificate Bundle (SIA): http://www.nextgenidtrust.com/PKI/certs/IssuedByNextgenIDRootCA1.p7c
OCSP: N/A

**Comment by indrajit-gsa** [comment]
#173 -- Pull request for this update.
