### ISSUE TITLE
FPKI Certificate and CRL Extensions Profile Guidance

### ISSUE THREAD

**Issue by MattKing1** [GSA/fpki-guides#17]
This playbook provides a description of how to use the [FPKI X.509 Certificate and CRL Extensions Profile](https://www.idmanagement.gov/IDM/servlet/fileField?entityId=ka0t0000000TNS1AAO&field=File__Body__s)

**Comment by dasgituser** [comment]
The how-to playbook will be new (not from an existing document).  The [FPKI X.509 Certificate and CRL Extensions Profile document](https://www.idmanagement.gov/IDM/servlet/fileField?entityId=ka0t0000000TNS1AAO&field=File__Body__s) will also be converted into markdown for publication on github.

**Comment by lachellel** [comment]
link to #24 and #25
