### ISSUE TITLE
FPKI Trust Infrastructure Overview

### ISSUE THREAD

**Issue by MattKing1** [GSA/fpki-guides#18]
This playbook provides an overview of the [FPKI Trust Infrastructure](https://www.idmanagement.gov/IDM/servlet/fileField?entityId=ka0t0000000TNRIAA4&field=File__Body__s)

**Comment by dasgituser** [comment]
This playbook has a wide target audience including but not limited to current and potential FPKI Community members, relying parties, agency managers and decisions makers. The document provides basic, essential context and understanding of the FPKI. It conveys some of the benefits/value of the FPKI as well as some of the core concepts (certificate policy and policy mapping, levels of assurance, path validation).  This playbook could be useful in increasing awareness, understanding, and use of the FPKI)

**Comment by lachellel** [comment]
This information should be broken down into sections and weaved into the demo guide pages (under /pages)

**Comment by dasgituser** [comment]
First full pass completed -- broken down into various relatively short sections/subsections that will fit into NavBar topology.  Content currently being reviewed internally prior to pull request submission.  "In progress" version was submitted last Friday 9/16/16.

**Comment by dasgituser** [comment]
This playbook will be broken apart into multiple playbooks per FPKI Navigation Bar structuring.  See also Issue #20

**Comment by djpackham** [comment]
We've added some content from this already to the current pages in the fpki-guides. Lets revisit this again after initial launch.

**Comment by ryancdickson** [comment]
@idmken - I think we can close this issue - overcome by events.

**Comment by idmken** [comment]
Incorporated this into the idm.gov content review.
