### ISSUE TITLE
Announcement for CT 

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#185]
#### Description of Issue: ####
- CT enforcement in Chrome will cause errors for intranet sites using TLS certificates issued from FPKI federal CAs
- Removal of TLS trust from Microsoft may mitigate a portion
- Impacts to MacOSx users

****** Migrated from #168 ********

@weirdscience @lachellel The edited, current version of the Google Announcement is here:
https://github.com/GSA/fpki-guides/edit/168-hot-topics/_announcements/02_google_ct.md

I added "coder" comments for questions that came up when I read the announcement.
For example: Google's use of CT introduces what problem for the FPKI?
Please take a look at the Markdown mark-up view to see these.
There are also still some placeholders in the file where text needs to be added.

Be glad to make any changes that you want.

**Comment by weirdscience** [comment]
Looks good to me. I added a short section on how to check compliance in Chrome.

**Comment by lachellel** [comment]
Thanks @weirdscience 

@clstmbrly - I committed some additional changes, including aligning with the format of the other 
announcement.

**Comment by clstmbrly** [comment]
Thanks @lachellel  Strangely coincidental--I was just thinking that I needed to check formatting consistency between the two:-).  Will take a look.

**Comment by lachellel** [comment]
#192
