### ISSUE TITLE
Add Search Box To FPKI Guides

### ISSUE THREAD

**Issue by indrajit-gsa** [GSA/fpki-guides#199]
#### Description of Issue: ####
There is no search feature in the FPKI Guides.

#### Details of Issue: ####
Add a search box to FPKI Guides and post the data to search.usa.gov. The feature will be similar to the one provided at idmanagement.gov.

#### References (Docs, Links, Files): ####
Should be added to the navbar.html and it will be included in all pages. Possibly replace the "View this site's code" button on the top navigation.

#### If a New Page or Content is Needed, Expected Outcomes: ####
New search box in FPKI Guides website.

**Comment by lachellel** [comment]
Update: 

- Search is covered in the www.idmanagement.gov site for search + results
- Leverages search dot gov
- There are also updates in design templates for jekyll - https://github.com/18F/uswds-jekyll#search

Backlog issue to be created to consider applying updated templates and best practices from uswds.  The current template in use is **old**.

**Comment by lachellel** [comment]
Reference changes made for piv guides - to add Search: 

- https://github.com/GSA/piv-guides/issues/207
- https://github.com/GSA/piv-guides/pull/244/commits/eba2d6bae5b77a5fc0106c19a91a9e0e866f77d0
