### ISSUE TITLE
Define structure for fpki-guides

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#20]
- Identify the audience, categories of information and navigation for fpki-guides
- For each above, add Labels to track and label associated issues

**Comment by djpackham** [comment]
@lachellel & @dasgituser proposed left navigation structure for FPKI-Guides.
- Introduction
- Federal PKI Overview
  - Federal PKI Trust Infrastructure
  - Other PKIs Participating in the Federal PKI
  - Some Things You Need to Understand When Participating in the Federal PKI
- Certificate Authorities
- CRL's and Certificates
  - Certificate Levels of Assurance
  - Certificate Mapping
  - Certificate Policies
  - Certificate Validation
- Personal Identity Verification Interoperable (PIV-I)
- Trust Stores
- Useful Tools
- User Guides
  - How to Identify Cross-certificates in the Federal PKI?
  - How to Digitally Sign a Document Using Microsoft Word or Adobe PDF?
  - How to Digitally Sign and Encrypt an Email Using Outlook?
  - How to Digitally Sign a Document in the Format Expected by the Federal Register?
- FAQ
  - What is Personal Identity Verification Interoperable (PIV-I)?
- Public Key Infrastructure (PKI) Fundamentals
  - What is Public Key Infrastructure?
  - Why Use PKI?
  - What are the Components of a PKI?
  - What is a Digital Signature?
  - What is Encryption?
  - What are the Different Types of Certificates and their Purpose?
- Glossary
- Contribute

**Comment by lachellel** [comment]
for minimum viable, let's get the top level bullets knocked out first - then we will work on the second level

**Comment by djpackham** [comment]
Sounds good! FYI, we were thinking PIV-I should probably be a separate nav item, as well as something in the FAQ section. (added PIV-I to comment above)

**Comment by lachellel** [comment]
@djpackham 

I'm working on a PR with the top level markdown and navigation 

After this PR goes in, let's map each issue that is being actively worked on to the target markdown placeholder?

**Comment by djpackham** [comment]
@lachellel - that works for me. @dasgituser mentioned he could break the recent overview file into the different sections once we have the markdown and navigation set.

**Comment by lachellel** [comment]
@djpackham 

take a look at the PR please?  I started to see the info, and changed some words in the navigation outline

If you agree with it, I'll merge. 
Then start taking each issue, and mapping to the target markdown file (or breaking down into smaller issues)

**Comment by lachellel** [comment]
@djpackham 

> Sounds good! FYI, we were thinking PIV-I should probably be a separate nav item, as well as something in the FAQ section. (added PIV-I to comment above)

I removed PIV-I entirely from navigation.  It can be a later add-on.  
- We don't cover PIV here, so why cover PIV-I?  
- Why not cover PIV-I in the PIV-Guides instead and anything that is too detailed - such as the _certificate policies_ for PIV-I or basic or medium or high assurance - we'd cover here ?

**Comment by djpackham** [comment]
@lachellel 

> take a look at the PR please? I started to see the info, and changed some words in the navigation outline

I agree with the PR for navigation :+1:
