### ISSUE TITLE
System Notification for: Retiring FBCA 2013

### ISSUE THREAD

**Issue by indrajit-gsa** [GSA/fpki-guides#200]
notice_date: April 4, 2018
change_type:  CA Certificate Revocation
start_datetime: 3/26/28 12:15PM EDT
end_datetime: 
system: SBCA Operational Authority
change_description: the cross-certificate from SBCA 02 to FBCA 2013 has been revoked (3/26/28 12:15PM EDT).  The CRL was published shortly thereafter.  We are updating repositories (SIA/AIA) today.
contact: Matthew dot Williams at exostar dot com
ca_certificate_hash: 
ca_certificate_issuer: 
ca_certificate_subject: 
cdp_uri: 
aia_uri: 
sia_uri: 
ocsp_uri:

**Comment by weirdscience** [comment]
Ready to close with #201 merge.
