### ISSUE TITLE
CTL Testing: SSA Results

### ISSUE THREAD

**Issue by cltross** [GSA/fpki-guides#220]
**Baseline Configuration:**
Windows 10 Enterprise, Build: 10.0.14393
Internet Explorer 11, Build: 11.2189.14393.0
Google Chrome, Build: 66.0.3359.139
Note: Unable to test with Edge due to GPO-controlled redirects to IE

**Comment by cltross** [comment]
**Test Procedures:**

**Comment by cltross** [comment]
**Test Procedures**

**Comment by weirdscience** [comment]
Thank you! Any results?

**Comment by cltross** [comment]
**Test Procedures**
1) Deleted Common and US Treasury Root CAs from Trust Store
2) Modified registry to pull test CTL:
Added:
New String: "RootDirUrl" http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en/USPKI
Deleted:
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SystemCertificates\AuthRoot\AutoUpdate\EncodedCtl]
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SystemCertificates\AuthRoot\AutoUpdate\LastSyncTime]
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SystemCertificates\AuthRoot\Certificates]
3) Restarted
4) Noted CTL would not automatically update
5) Manually downloaded test CTL, http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en/USPKI/authroot.cab, and extracted authroot.stl
6) Imported the CTL using certutil -addstore -f AuthRoot authroot.stl
7) Verified CTL using certutil -verifyCTL AuthRoot
8) Verified CTL from Trust Store using certmgr.msc
9) Verified Web Server Certificate showed full chain to common policy and did not include Server Authentication as an application policy (certutil -verify webserver.cer)
10) Cleared browser cache and accessed internal webservers

**Results**
IE Error:
There is a problem with this website’s security certificate.
The security certificate presented by this website is not secure.
Security certificate problems may indicate an attempt to fool you or intercept any data you send to the server.
We recommend that you close this webpage and do not continue to this website 

Chrome Error:
Your connection is not private.
Attackers might be trying to steal your information from <web server> (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_INVALID

11) Restored production CTL in the registry
Modified String: "RootDirUrl" http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en
Deleted:
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SystemCertificates\AuthRoot\AutoUpdate\EncodedCtl]
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SystemCertificates\AuthRoot\AutoUpdate\LastSyncTime]
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SystemCertificates\AuthRoot\Certificates]

12) Verified prodcution CTL using certutil -verifyCTL AuthRoot
13) Verified Web Server Certificate showed full chain to common policy and did not include the extra application policy OID to disallow.
**Results**:
IE, Chrome: Successfully loaded web server pages

14) Reverted back to the tst CTL and verified SSA GPO controlled trust stores compensate for server auth disallow by adding Common and US Treasury root  (gpupdate /force)
**Results**:
IE, Chrome: Successfully loaded web server pages

**Comment by weirdscience** [comment]
Testing is complete.
