### ISSUE TITLE
System Notification for: Railroad Retirement Board CA (Digicert)

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#226]
notice_date: 5/16/2018
change_type:  CA Certificate Revocation
start_datetime:  5/21/2018
end_datetime:  
system: Digicert / Verisign / Symantec federal shared service provider
change_description:  The Railroad Retirement Board CA will be retired, and a revocation of the CA certificate will occur on May 21, 2018.  
contact: fpki@gsa.gov
ca_certificate_hash: 
ca_certificate_issuer: CN=VeriSign SSP Intermediate CA - G3,O=VeriSign,Inc.,C=US
ca_certificate_subject: CN=RRB Device CA,OU=U.S. Railroad Retirement Board,OU=U.S. Railroad Retirement Board,O=U.S. Government,C=US

**Comment by lachellel** [comment]
[update]

notice_date: 5/16/2018
change_type: CA Certificate Revocation
start_datetime: 5/18/2018
end_datetime:
system: Digicert / Verisign / Symantec federal shared service provider
change_description: The Railroad Retirement Board CA was decommissioned and a long-term CRL issued on May 18, 2018
contact: fpki@gsa.gov
ca_certificate_hash:
ca_certificate_issuer: CN=VeriSign SSP Intermediate CA - G3,O=VeriSign,Inc.,C=US
ca_certificate_subject: CN=RRB Device CA,OU=U.S. Railroad Retirement Board,OU=U.S. Railroad Retirement Board,O=U.S. Government,C=US

**Comment by weirdscience** [comment]
Updating system notification.

**Comment by weirdscience** [comment]
Ready to close after #252 merge.

**Comment by weirdscience** [comment]
Added to #201 and closed #252
