### ISSUE TITLE
PIV-I for Non-federal Issuers

### ISSUE THREAD

**Issue by dasgituser** [GSA/fpki-guides#23]
@dasgituser will convert the [PIV-I for NFI document](https://cio.gov/wp-content/uploads/downloads/2012/09/PIV_Interoperabillity_Non-Federal_Issuers_May-2009.pdf) to a playbook (started but currently on hold).  The playbook provides solutions for overcoming the barriers to federal reliance on non-federal identity cards, and summarizes some of the core PIV-I requirements.  Better understanding the PIV-I concept and associated core requirements, as well as knowing where to go for the full set of PIV-I requirements should help potential PIV-I Providers as well as federal relying parties.

**Comment by lachellel** [comment]
Don't think we need this right now (low to no priority).   

The PIV-I for NFI doc is a CIO Council artifact and has Policy behind it
addressing through the CIO Councils first

**Comment by lachellel** [comment]
piv-i was updated.
