### ISSUE TITLE
FPKI AIA webcrawler site is down

### ISSUE THREAD

**Issue by funkmaxwell** [GSA/fpki-guides#231]
#### Description of Issue: ####
https://fpki-graph.fpki-lab.gov/crawler/
FPKI WebCrawler site produces "This site can't be reached" errors in IE and Chrome.

#### Details of Issue: ####
Seems to be due to timeout error.  Impacts ability to efficiently download cert packages/trust chains cross certified with FBCA.

#### Link to the Content Page for Contributors: ####
https://fpki-graph.fpki-lab.gov/crawler

**Comment by lachellel** [comment]
hi @funkmaxwell 

The fpki graph was moved to this github repo, and the fpki playbook site.  Unfortunately the original URL doesn't redirect. 

The graph can be found at: https://fpki.idmanagement.gov/tools/fpkigraph/

https://fpki.idmanagement.gov -> Under "Tools" in the left hand navigation -> FPKI Graph

**Comment by funkmaxwell** [comment]
Thanks @lachellel, do you all still have the consolidated p7b outputs for download as well?

**Comment by ryancdickson** [comment]
We have received an additional request to support p7b generation from DC.gov.

[For more information, see email to fpki@gsa.gov from Stephan Papadopulos.]

**Comment by clstmbrly** [comment]
@lachellel We recommend that this issue be closed. 
@ryancdickson

**Comment by ryancdickson** [comment]
Closing issue. P7B Generation has been deprecated from Crawler code. If folks think this should be reopened, please let me know.
