### ISSUE TITLE
Update CT Announcement for Apple's Planned Implementation

### ISSUE THREAD

**Issue by ryancdickson** [GSA/fpki-guides#235]
#### Description of Issue: ####
Apple has released details regarding its planned CT implementation. Update existing announcement to include updated Apple verbiage.

#### Details of Issue: ####
[ See above ]

#### References (Docs, Links, Files): ####
https://support.apple.com/en-us/HT205280

**Comment by ryancdickson** [comment]
Last update: Contacted Apple on 07 August for CT related updates.

**Comment by clstmbrly** [comment]
Awaiting updated CT implementation details from Apple.

**Comment by lachellel** [comment]
@ryancdickson can this be closed?

**Comment by ryancdickson** [comment]
Given that COMMON will not face CT enforcement due to its removal from the Apple certificate stores, I think we are safe to close.
