### ISSUE TITLE
SSP Certificate and CRL Extensions Profile Guidance

### ISSUE THREAD

**Issue by dasgituser** [GSA/fpki-guides#24]
This playbook provides a description of how to use the [SSP X.509 Certificate and CRL Extensions Profile](https://www.idmanagement.gov/IDM/servlet/fileField?entityId=ka0t0000000TNP2AAO&field=File__Body__s).  This will help Shared Service Providers operating within the FPKI to better understand and utilize the Profile, which is essential for establishing commonality and interoperability within the FPKI.  This how-to playbook will be new (not from an existing document). The [SSP X.509 Certificate and CRL Extensions Profile document](https://www.idmanagement.gov/IDM/servlet/fileField?entityId=ka0t0000000TNP2AAO&field=File__Body__s) will also be converted into markdown for publication on github.

**Comment by lachellel** [comment]
link to #25 and #17 

summarize, not replace the documents yet

From a PKI Operator / Provider perspective - a simple table / section that compares and contrasts:
- what are the differences between the profiles for an SSP vs FPKI vs PIV-I?
- why is it different?
- what are the commonalities?
- where do I go to learn / read more (link to doc)
