### ISSUE TITLE
Trust Store page update to align with current removal announcements

### ISSUE THREAD

**Issue by weirdscience** [GSA/fpki-guides#244]
#### Description of Issue: ####
The FPKI Guide hosts a "Trust Store" page which explains how and where COMMON is trusted in trust stores. COMMON is being removed and this page provides conflicting information.

#### Details of Issue: ####
The Trust Store page provides conflicting information with the latest public trust announcements.

#### References (Docs, Links, Files): ####
https://fpki.idmanagement.gov/truststores/
https://devicepki.idmanagement.gov/
https://fpki.idmanagement.gov/announcements/applepkichanges/
https://fpki.idmanagement.gov/announcements/mspkichanges/

#### If a New Page or Content is Needed, Expected Outcomes: ####
The update should remove conflicting information and reference the announcements and device PKI

#### Link to the Content Page for Contributors: ####
https://fpki.idmanagement.gov/truststores/

**Comment by clstmbrly** [comment]
@weirdscience Thanks for putting this out.  An issue was my to-do list:-)  

We also need to update the PIV-Guides' Certificate Trust page: https://piv.idmanagement.gov/pivcertchains/
