### ISSUE TITLE
System Notification for: Certipath Bridge

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#245]
notice_date: June 13, 2018
change_type:  CA Certificate Issuance
start_datetime:  
system: Certipath Bridge CA
change_description: 
contact: 
ca_certificate_hash: 
ca_certificate_issuer: 
ca_certificate_subject: 
cdp_uri: 
aia_uri: 
sia_uri: 
ocsp_uri:
 
************************* Email ************************
Intent to renew the cross certificates from the CertiPath Bridges to Raytheon prior to the end of this month. No changes are being made to certificate policies or policy mappings.

The following certificates will be renewed until June 30 2019:
CertiPath Bridge CA - G2  Raytheon Root CA
Validity Period: June 28, 2017, 8 p.m. - June 30, 2018, 7:59 p.m.

CertiPath Bridge CA  RaytheonRoot
Validity Period: June 28, 2017, 8 p.m. - June 30, 2018, 7:59 p.m.

**Comment by weirdscience** [comment]
Added to #201 and closed #252
