### ISSUE TITLE
PIV-I Certificate and CRL Extensions Profile Guidance

### ISSUE THREAD

**Issue by dasgituser** [GSA/fpki-guides#25]
This playbook provides a description of how to use the [PIV-I X.509 Certificate and CRL Extensions Profile](https://www.idmanagement.gov/IDM/servlet/fileField?entityId=ka0t0000000GmhKAAS&field=File__Body__s). This will help PIV-I Card Issuers operating within the FPKI to better understand and utilize the Profile, which is essential for establishing commonality and interoperability within the FPKI. This how-to playbook will be new (not from an existing document). The [PIV-I X.509 Certificate and CRL Extensions Profile document](https://www.idmanagement.gov/IDM/servlet/fileField?entityId=ka0t0000000GmhKAAS&field=File__Body__s) will also be converted into markdown for publication on github.

**Comment by lachellel** [comment]
I think the document stays as a document for now, and the guide Summarizes.
