### ISSUE TITLE
Where to request a certificate revocation due to compromise

### ISSUE THREAD

**Issue by weirdscience** [GSA/fpki-guides#253]
#### Description of Issue: ####
There is no readily accessible location to report a certificate compromise.

#### Details of Issue: ####
There should be a readily accessible location to report a certificate compromise.

#### References (Docs, Links, Files): ####
Bridge and Common CP and CPS

#### If a New Page or Content is Needed, Expected Outcomes: ####
The new page or content should say "To report or a request a revocation due to a suspected Private Key Compromise, Certificate misuse, or other types of fraud, compromise, misuse, inappropriate conduct, or any other matter related to certificates, send an email to fpki@gsa.gov"

**Comment by coolmary** [comment]
Excellent Programs and easy to access,programs and keys,thanks so much.

**Comment by weirdscience** [comment]
@lachellel this came up a couple months ago during our audit. There's no central place for someone to report compromises or mis-issuances to the policy authority. I think It might need a page, but this is a start. What do you think?

Trying to knock out some issues :1st_place_medal:

**Comment by weirdscience** [comment]
This has moved to an idmangement.gov update.
