### ISSUE TITLE
Community Interoperability Test Environment  (CITE) Participation  Guidance 

### ISSUE THREAD

**Issue by dasgituser** [GSA/fpki-guides#26]
The FPKI Management Authority's [Community Interoperability Test Environment (CITE) Participation Guidance](https://www.idmanagement.gov/IDM/servlet/fileField?entityId=ka0t0000000TNpPAAW&field=File__Body__s) will be converted into a playbook.  CITE provides  the  FPKI Community  with  
a  test environment to:  (1) identify and  resolve technical issues across Affiliates PKIs, and (2) ensure proper functionality of respective system changes prior to deploying them in a production  environment.  The Guidance document informs and instructs FPKI Affiliates how to access and use CITE.  Encourageing use (and proper use) helps create more robust/reliable FPKI consistency and proper functioning.

**Comment by weirdscience** [comment]
You can assign this to me.

**Comment by clstmbrly** [comment]
@weirdscience Should this Issue (2016) be closed?  Thanks much.

**Comment by weirdscience** [comment]
I converted the guide, but never got around to loading it. Should I load it somewhere?

**Comment by weirdscience** [comment]
I created a branch and loaded the CITE guide.

**Comment by weirdscience** [comment]
A CITE Guide update was assigned as an action at the last TWG. The MA team is working on a first draft.

**Comment by weirdscience** [comment]
fixed by #409
