### ISSUE TITLE
Obtaining a Credential to Access a Federal Application

### ISSUE THREAD

**Issue by dasgituser** [GSA/fpki-guides#27]
This playbook would be new -- not derived from an existing document.  The playbook would explain the various contexts and steps for a citizen to obtain a credential to access a federal system.  This might include a TFS scenario, PIV-I Card scenario, direct from agency scenario, etc.  The target audience is primarily citizens, but others (e.g., credential issuers, relying parties) might also be interested.

**Comment by lachellel** [comment]
No.  **Citizens** are covered by other form factors and scenarios for government.  

It can be Businesses and Partners (State and Local, etc), but not Citizens / Consumers.  

No to low priority for this issue / guide.

**Comment by weirdscience** [comment]
Would this be a pointer of where to find business and citizen credentials on idmanagment.gov instead of a playbook?

**Comment by clstmbrly** [comment]
Viable idea for business and partners?  Keep or close?
