### ISSUE TITLE
FPKI Mapping Tables Playbook

### ISSUE THREAD

**Issue by dasgituser** [GSA/fpki-guides#28]
This would be new -- not a conversion of an existing document.  The FPKI has two different mapping tables. The [FPKI Applicant Certification Mapping Table](https://www.idmanagement.gov/IDM/s/document_detail?Id=kA0t00000008OcnCAE)is used by non-SSPs to map their Certificate Policy against the FBCA Certificate Policy.  The [FPKI Common Policy Framework CPS Evaluation Table](https://www.idmanagement.gov/IDM/s/document_detail?Id=kA0t0000000KyrfCAC) is for SSPs to map their Certification Practice Statement against FCPCA Certificate Policy The mapping tables are used during the application (full mapping) process and subsequent audits (delta mappings).  This playbook will explain the differences between the mapping tables, when to use, and how to use.

Target audience are FPKI Affiliates/SSPs who must complete the applicable mapping tables, as well as auditors that will facilitate use of the mapping tables and review completed mappings.

**Comment by lachellel** [comment]
The information should be a summary and general overview of the mapping, the audits, etc.

**Comment by weirdscience** [comment]
@lachellel, I'm looking over old issues. The mapping table links are no longer active and this may be an FPKI audit playbook based on the annual review requirements. Are the annual review requirements scheduled to be converted at some point?

**Comment by idmken** [comment]
How to perform a mapping is covered in the application process document.
