### ISSUE TITLE
Microsoft trust store instructions - highlight privileges

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#280]
#### Description of Issue: ####
Questions on privileges needed **and** where the commands are run for the re-distribution of Common to a network domain

#### Details of Issue: ####
The instructions state ent admin privileges and domain controller(s).  We should consider highlighting this dependency with an info alert prior to the detailed instructions. 

#### References (Docs, Links, Files): ####
https://github.com/GSA/fpki-guides/blob/staging/_includes/microsoft_trust_store_installation.md

#### Link to the Content Page for Contributors: ####
https://github.com/GSA/fpki-guides/blob/staging/_includes/microsoft_trust_store_installation.md

**Comment by ryancdickson** [comment]
I believe we have addressed this issue in the latest updates to the MSFT Solutions page.

Recommend closure.

**Comment by clstmbrly** [comment]
@lachellel This information was added via info-alerts to the latest published MSFT Removal Announcement and MSFT Solutions pages.  Closing this issue.
@ryancdickson
