### ISSUE TITLE
Agency Guide to FPKI Credentials

### ISSUE THREAD

**Issue by dasgituser** [GSA/fpki-guides#29]
This would be new -- not based on any particular existing document.  Target audience is agency relying parties.  Guide would address topics such as:
1. Making agencies aware of different types of FPKI credentials 
2. Determining which to accept for their applications
3. Education / facilitation of agency end user populations obtaining those credentials
4. How to configure agency system to accept the selected credentials
5. PKI-specific enrollment/activation (if not fully covered in another playbook that we are aware of)

**Comment by lachellel** [comment]
Let's break these into five (5) different issues and blurbs.  Just like the bullets. 
- Bullet 1 - different types?  This is a perfect, small, short, no acronym section.  Medium to high priority?
- Bullet 2 - which to accept?  No priority for now.  This is based on risk assessments and we want to align with 800-63-3 draft and forward thinking changes in progress. 
- Bullet 3 - obtaining credentials?  Low priority.  
- Bullet 4 is being covered elsewhere (slowly) and most certainly can't be covered in one generic guide!
- Bullet 5 - needs more info

**Comment by dasgituser** [comment]
This issue should now be considered No Action / Closed since it has been broken into separate issues - see above.

**Comment by lachellel** [comment]
closed
