### ISSUE TITLE
How to Digitally Sign and Encrypt - Guide for Agency employees and contractors

### ISSUE THREAD

**Issue by dasgituser** [GSA/fpki-guides#30]
This would be new -- not based on any particular existing document.  Target audience is agency relying parties and their staff.  Guide would address topics such as:
1. how to digitally sign, encrypt, verify signatures, authenticate, etc
2. Emphasize benefits to RP applications/owners
3. special considerations such as what to do once you verify a digital signature (archive to be able to verify after certificate expiration)

**Comment by lachellel** [comment]
Issues is specific to Digital Signatures and Encryption (updated issue title)

What is the target technologies?  Email (s/mime)?  Documents?

**Comment by dasgituser** [comment]
At least those to start with.  Over time, we can add others as requested/needed.

**Comment by weirdscience** [comment]
This should move to the PIV Guide.

**Comment by weirdscience** [comment]
Transferred to PIV Guide as an issue.
