### ISSUE TITLE
System Notification for: Federal PKI Trust Infrastructure (Treasury)

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#306]
notice_date: 8/22/2019
change_type:  CA Certificate Issuance 
start_datetime: 8/22/2019 
system: Federal PKI Trust Infrastructure - Federal Common Policy CA
change_description:  Issuance of a cross-certificate from the Federal Common Policy CA to the US Treasury Root CA will occur in the next two weeks, and the certificate artifact will be published.. 
contact: fpki@gsa.gov
ca_certificate_hash: 
ca_certificate_issuer: 
ca_certificate_subject:  CN = US Treasury Root CA OU = Certification Authorities OU = Department of the Treasury O = U.S. Government C = US
cdp_uri: 
aia_uri: 
sia_uri: 
ocsp_uri:

**Comment by weirdscience** [comment]
notice_date: 9/7/2018
change_type: CA Certificate Issuance
start_datetime: 8/22/2019
system: Federal PKI Trust Infrastructure - Federal Common Policy CA
change_description: Issuance of a cross-certificate from the Federal Common Policy CA to the US Treasury Root CA.
contact: fpki@gsa.gov
ca_certificate_hash: ‎5a 87 92 2b 5e af 1d 63 19 8a 95 1b 2a b6 f5 9b 2f 16 c1 31
ca_certificate_issuer: CN = Federal Common Policy CA OU = FPKI O = U.S. Government C = US
ca_certificate_subject: CN = US Treasury Root CA OU = Certification Authorities OU = Department of the Treasury O = U.S. Government C = US
cdp_uri: http://http.fpki.gov/fcpca/fcpca.crl
aia_uri: http://http.fpki.gov/fcpca/caCertsIssuedTofcpca.p7c
sia_uri: http://pki.treasury.gov/root_sia.p7c
ocsp_uri: N/A
