### ISSUE TITLE
Agency-focused PIV-I FAQ 

### ISSUE THREAD

**Issue by dasgituser** [GSA/fpki-guides#31]
Will be a compilation of material in various places including the existing PIV-I FAQ.  Will also leverage / build upon similar playbook LaChelle has already started.  Target audience is agency relying parties.  FAQ content would include things such as:
1. high-level explanation of what PIV-I is and use cases / benefits
2. What Is The Difference Between A PIV-I Card And A PIV Card?
3. Can My Agency Accept PIV-I Cards Issued By Our Contractors’ Company In Lieu Of Issuing PIV Cards To These Individuals?
4. Can A PIV-I Card Be Accepted For Both Physical And Logical Access?
5. As A Relying Party, When Do I Use The FASC-N Versus GUID?

**Comment by dasgituser** [comment]
In development by Jason Sargent

**Comment by idmken** [comment]
@ryancdickson @sarahdobson I think the majority of this is covered by the PIV-I for Issuers guidance.

https://www.idmanagement.gov/wp-content/uploads/sites/1171/uploads/piv-i-for-issuers.pdf

**Comment by ryancdickson** [comment]
@idmken - I agree

**Comment by idmken** [comment]
We can open a new issue to convert the PIV-I for issuers if needed. That is a CIO Council document.
