### ISSUE TITLE
System Notification for: SAFE Biopharma

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#312]
notice_date: 8/23/2018
change_type:  CA Certificate Issuance
start_datetime: 8/23/2018
system: SAFE-Biopharma Bridge Certification Authority (NH-ISAC)
change_description: New cross-certificate issued from SAFE-Biopharma Bridge Certification Authority to the Federal Bridge CA 2016
contact: dsimonetti at safe-biopharma dot org
ca_certificate_hash: 
ca_certificate_issuer: 
ca_certificate_subject: 
cdp_uri: 
aia_uri: 
sia_uri: 
ocsp_uri:
 

**********************

To All SAFE-BioPharma Certificate Issuers:

The SAFE-BioPharma Bridge Certification Authority (SBCA) will be issuing a cross-certificate to the Federal Bridge Certification Authority (FBCA) today to replace the current cross-certificate that expires at the end of today.  New to this cross-certification is the addition of explicit machine-to-device mappings at medium-Software and medium-Hardware assurance levels.

**Comment by davidsimonetti** [comment]
ca_certificate_hash:  540c2ac59f8b5bab1b6adf421a7c50f0901e3d54
ca_certificate_issuer: CN = SAFE Bridge CA 02, OU = Certification Authorities, O = SAFE-Biopharma, C = US
ca_certificate_subject: CN = Federal Bridge CA 2016, OU = FPKI, O = U.S. Government, C = US
cdp_uri: http://sbca2.safe-biopharma.org/sbca/SBCA02.crl
aia_uri: http://sbca2.safe-biopharma.org/sbca/issuedtoSBCA02.p7c
sia_uri:  http://http.fpki.gov/bridge/caCertsIssuedByfbca2016.p7c
