### ISSUE TITLE
System Notification for: SAFE-BioPharma Bridge

### ISSUE THREAD

**Issue by davidsimonetti** [GSA/fpki-guides#316]
notice_date: August 30, 2018
change_type:  CA Certificate Issuance 
start_datetime: 
end_datetime: 
system: 
change_description: Notification of the SAFE-BioPharma Bridge Certification Authority (SBCA) intent to issue a new cross-certificate to IdenTrust SAFE-BioPharma CA 1
contact: David Simonetti, dsimonetti@safe-biopharma.org
ca_certificate_hash: 
ca_certificate_issuer: 
ca_certificate_subject: 
cdp_uri: 
aia_uri: 
sia_uri: 
ocsp_uri:

**Comment by davidsimonetti** [comment]
The new Identrust SAFE-BioPharma CA 1 cross-certification does not introduce multiple paths to a CA already participating in the FPKI.

**Comment by lachellel** [comment]
@davidsimonetti any info on this cert?  

I can crawl the SIAs if they are published...

**Comment by davidsimonetti** [comment]
They have not been generated nor issued yet.  We’re working through legal issues between entities, not technical, but we should come to a mutual agreement soon.

 

Regards,

David Simonetti

**Comment by davidsimonetti** [comment]
notice_date: December 19, 2018
change_type: CA Certificate Issuance
start_datetime: December 19, 2018
end_datetime:
system: SAFE-BioPharma Bridge CA
change_description: A cross-certificate was issued to IdenTrust SAFE-BioPharma CA 1
contact: dsimonetti@safe-biopharma.org
ca_certificate_hash: 245f753f8a315a83bd0be8cf70833503f99fd2d2
ca_certificate_issuer: CN = SAFE Bridge CA 02, OU = Certification Authorities, O = SAFE-Biopharma, C = US
ca_certificate_subject: CN = IdenTrust SAFE-BioPharma CA 1, OU = IdenTrust Global Common, O = IdenTrust, C = US
cdp_uri: http://sbca2.safe-biopharma.org/sbca/SBCA02.crl
aia_uri: http://sbca2.safe-biopharma.org/sbca/issuedtoSBCA02.p7c
sia_uri:
ocsp_uri:
