### ISSUE TITLE
Explaining different types of FPKI User / Person Certificates

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#32]
#29 breakdown

This would be new -- not based on any particular existing document. Target audience is agency relying parties. Guide would address topics such as:

Making agencies aware of different types of FPKI credentials
- Focus on Persons
- Short succinct information on types (basic, medium, med hw, etc) - in non acronym terms
- Mapping table or diagram to the identity assurance for each
  - what is needed such as in-person, biometrics, no biometrics, remote, etc

@dasgituser thoughts?

**Comment by dasgituser** [comment]
I really like that.  I think that info will greatly help relying parties.  We'll look to see what other similar kinds of info we can include.  Thanks!

**Comment by lachellel** [comment]
#33

**Comment by lachellel** [comment]
Where would this map to in initial outline #20  ?

**Comment by dasgituser** [comment]
Assigned to Jason Sargent

**Comment by idmken** [comment]
PIV certs are addressed on https://piv.idmanagement.gov/details/
