### ISSUE TITLE
Repository Availability Table

### ISSUE THREAD

**Issue by ryancdickson** [GSA/fpki-guides#325]
@weirdscience 

#### Description of Issue: ####
The "Repository Availability" table (https://fpki.idmanagement.gov/tools/fpkiactivityreport/) appears to have two columns for September 2017, and no entry for July 2018. Highlighting this for review.

#### Details of Issue: ####
Please see above.

#### References (Docs, Links, Files): ####
https://fpki.idmanagement.gov/tools/fpkiactivityreport/

#### If a New Page or Content is Needed, Expected Outcomes: ####
If table is as expected, please disregard this issue submission.

#### Link to the Content Page for Contributors: ####
https://fpki.idmanagement.gov/tools/fpkiactivityreport/

**Comment by weirdscience** [comment]
Thanks @ryancdickson. This should fix it.

**Comment by ryancdickson** [comment]
Awesome, thanks @weirdscience. I'll close!
