### ISSUE TITLE
What Are The Different Types of FPKI Credentials

### ISSUE THREAD

**Issue by dasgituser** [GSA/fpki-guides#33]
Derives from Issue #29 

Make agencies aware of different types of FPKI credentials 

LaChelle: different types? This is a perfect, small, short, no acronym section. Medium to high priority?

**Comment by dasgituser** [comment]
This would be new -- not based on any particular existing document. Target audience is agency relying parties

**Comment by lachellel** [comment]
Where would this map to in the outline ( #20 )?

**Comment by lachellel** [comment]
duplicate of #32

**Comment by lachellel** [comment]
closing as duplicate

**Comment by weirdscience** [comment]
#32, #34 and this one are related and very similar to content we put together for the ACES transition. I can convert the ACES transition guide and work on this.
