### ISSUE TITLE
How Do I Determine Which Credentials to Accept

### ISSUE THREAD

**Issue by dasgituser** [GSA/fpki-guides#34]
Derives from Issue #29 

This would be new -- not based on any particular existing document. Target audience is agency relying parties....

Determine which to accept for their applications

LaChelle: which to accept? No priority for now. This is based on risk assessments and we want to align with 800-63-3 draft and forward thinking changes in progress.

**Comment by idmken** [comment]
A process to select a IAL, AAL, or FAL is covered in the Digital Identity Risk Assessment Playbook.
