### ISSUE TITLE
How To Configure Agency Systems To Accept Selected Credentials

### ISSUE THREAD

**Issue by dasgituser** [GSA/fpki-guides#36]
This derives from Issue #29 

This would be new -- not based on any particular existing document. Target audience is agency relying parties.....

```
    How to configure agency system to accept the selected credentials
```

LaChelle: is being covered elsewhere (slowly) and most certainly can't be covered in one generic guide!

**Comment by idmken** [comment]
PIV Guide covers how to configure for network authentication. The upcoming SSO playbook includes how to plan for authenticators.
