### ISSUE TITLE
System Notification for: Verizon SSP CA A2

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#365]
notice_date: November 20, 2018
change_type:  CA Certificate Issuance
start_datetime: 
system: FPKI Trust Infrastructure - Federal Common Policy CA
change_description:  Issuance of a modified subordinate CA certificate from the Federal Common Policy CA to the Verizon SSP CA A2.  The modification will add a new policy object identifier. 
contact: fpki dash help at GSA dot gov
ca_certificate_hash: 
ca_certificate_issuer: CN = Federal Common Policy CA, OU = FPKI, O = U.S. Government, C = US
ca_certificate_subject: CN = Verizon SSP CA A2,OU = SSP,O = Verizon,C = US
cdp_uri: http://http.fpki.gov/fcpca/fcpca.crl
aia_uri: 
sia_uri: 
ocsp_uri:

**Comment by lachellel** [comment]
@weirdscience does this CA cert mod have an update (timeline)?

**Comment by weirdscience** [comment]
Issued this week and waiting for acceptance from Verizon.
