### ISSUE TITLE
Federal PKI root

### ISSUE THREAD

**Issue by ashafiqiaf** [GSA/fpki-guides#369]
#### Description of Issue: ####
I have applied the GPO as explain in the guide and I have also imported the certificate manually but I do not see the other two certificates. Not under " Trusted Root Authority" and neither under "Enterprise" sub-directory.

#### Details of Issue: ####
11/29/2018

**Comment by ryancdickson** [comment]
Issue resolved via email, following up here for record:

There are two additional ways you can verify COMMON's redistribution on an end-point, presented below. To be sure your GPO is working as expected, I'd recommend checking a few hosts using one of these options.

**Option 1: Viewing the Physical Stores within Microsoft Certificate Manager**

- Click the Windows Start icon, type certlm.msc, and then press Enter.
- From the left hand side of the certlm application window, (single) click on the "Trusted Root Certification Authorities" folder icon to highlight it
- Along the top menu, click "View" -> "Options"
- Ensure the "Show the following: Physical certificate stores" checkbox is checked. Click OK
- From the left hand side, double click on the "Trusted Root Certification Authorities" folder to reveal its sub-folders
- Double-click on "Group Policy", and then "Certificates" to reveal trusted root certificates distributed to the client via GPO. 
- You should see a copy of COMMON here, if successfully redistributed via GPO.

**Option 2: Checking the Registry**
When COMMON is distributed via GPO, you should see the following additions to a client's registry...

- HKLM:\SOFTWARE\Policies\Microsoft\SystemCertificates\Root\Certificates\905F942FD9F28F679B378180FD4F846347F645C1\
- HKLM:\SOFTWARE\WOW6432Node\Policies\Microsoft\SystemCertificates\Root\Certificates\905F942FD9F28F679B378180FD4F846347F645C1\
