### ISSUE TITLE
How To Enroll/Activate PKI-credential End Users

### ISSUE THREAD

**Issue by dasgituser** [GSA/fpki-guides#37]
This derives from Issue #29

This would be new -- not based on any particular existing document. Target audience is agency relying parties.....

PKI-specific enrollment/activation (if not fully covered in another playbook that we are aware of)

LaChelle: needs more info

@dasgituser:  how-to guide describing what a relying party application needs to do to map the asserted identity to some provisioned account in the system.  I believe FICAM Roadmap discusses this topic in general, so we might leverage that material and frame it in terms of PKI certificates.

**Comment by lachellel** [comment]
this might be better to frame out in the area of applications (under piv-guides) and the patterns we're pulling into over there...??

there are a few patterns that are mapped out in ficam roadmap, ficam architecture, and related documentation (including the federation working group documents)

you are correct that the Federal PKI specific authentication event is not addressed well

let's break this one down with bullets and thoughts here before we start configuring and writing
- Web applications?
- Client applications?
- Networks? 
- Single sign on / web access managers?
- is this for persons (not devices)?

**Comment by lachellel** [comment]
Closing

**Comment by idmken** [comment]
Some elements covered in the PIV Guide and in the upcoming SSO Playbook.
