### ISSUE TITLE
Why is Alexion Pharmaceuticals showing as the root cert for many .mil sites?

### ISSUE THREAD

**Issue by DanielVF** [GSA/fpki-guides#384]
Why is Alexion Pharmaceuticals showing as the root cert for many .mil sites? Is this intentional?

![image](https://user-images.githubusercontent.com/837/50378809-b05e8400-0608-11e9-96c7-f71b452c5a06.png)

**Comment by grandamp** [comment]
It depends.  

Was this path built through a web browser (or user agent) during a TLS session?  If so, which one?  

Or, are you observing a possible path?  

There are *many* possible paths, to all CAs within the FPKI, via FBCA2016.

**Comment by DanielVF** [comment]
This was from the latest Chrome. I've checked around with some friends and they are seeing it as well. 

After reading up on cross signing, the tech side makes sense. It just looks strange!
