### ISSUE TITLE
CITE Guide Update - Treasury Comments

### ISSUE THREAD

**Issue by weirdscience** [GSA/fpki-guides#389]
- [x] 3. (in general): Are these normative requirements, or, are there informative statements included?
a. I.e., 3(b):  “All CAs must have the name “Test” in the Distinguished Names (DNs)…”
b. All of Treasury’s development CAs (cross-certified with CITE, inclusive of SSP customers) have “Development” in the issuer name.
c. This will not be changing anytime soon.
d. This would appear to suggest that “Test” appear in every “Distinguished Name” value, which would not only affect issuer, but subject fields as well.

- [ ] 4. (in general):  This seems informative, as I would assume it is not an attempt to instruct affiliates how to conduct testing.  Unless there is a requirement to make private keys accessible to everyone, and not *only* the entity that the corresponding certificate was issued to.

- [ ] 5. (in general):  normative / informative?

**Comment by weirdscience** [comment]
Corrected your 3 question in the doc @grandamp . The intent is for CAs to be distinctly marked in a way you can tell it is a test/dev CA.

**Comment by grandamp** [comment]
Thanks!
