### ISSUE TITLE
System Notification for: STRAC Bridge CA

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#401]
notice_date: February 11, 2019
change_type:  CA Certificate Issuance 
start_datetime: 
system: FPKI Trust Infrastructure - Federal Bridge 2016
change_description: New cross-certificate issued from Federal Bridge CA 2016 to STRAC Bridge Root Certification Authority
contact: fpki at gsa dot gov
ca_certificate_hash: 
ca_certificate_issuer: 
ca_certificate_subject: 
cdp_uri: 
aia_uri: 
sia_uri: 
ocsp_uri:

**Comment by weirdscience** [comment]
The certificate has been issued

notice_date: February 15, 2019
change_type: CA Certificate Issuance
start_datetime: February 14, 2019
system: FPKI Trust Infrastructure - Federal Bridge 2016
change_description: New cross-certificate issued from Federal Bridge CA 2016 to STRAC Bridge Root Certification Authority
contact: fpki at gsa dot gov
ca_certificate_hash: ‎1f 92 eb 36 54 f6 0a 90 92 81 1f 79 48 af ff 45 c0 9a 6c a9	
ca_certificate_issuer: CN = Federal Bridge CA 2016, OU = FPKI, O = U.S. Government, C = US
ca_certificate_subject: CN = STRAC Bridge Root Certification Authority, OU = STRAC PKI Trust Infrastructure, O = STRAC, C = US
cdp_uri: http://http.fpki.gov/bridge/fbca2016.crl
aia_uri: http://http.fpki.gov/bridge/caCertsIssuedTofbca2016.p7c
sia_uri: http://pki.strac.org/bridge/certificates/STRACBridgeRootCA.p7c
ocsp_uri: N/A

**Comment by ryancdickson** [comment]
Closing issue. If done in error, please let me know.
