### ISSUE TITLE
System Notification for: FPKI Trust Infrastructure - Federal Common Policy

### ISSUE THREAD

**Issue by weirdscience** [GSA/fpki-guides#403]
notice_date: February 12, 2019
change_type:  CA Certificate Revocation
start_datetime: December 9, 2010
end_datetime: December 9, 2020
system: FPKI Trust Infrastructure - Federal Common Policy CA
change_description: Revocation of the Verizon Betrusted Production SSP CA A1
contact: FPKI dash help at gsa dot gov
ca_certificate_hash: ‎06 01 bb da d5 a2 82 31 bc 94 36 75 0b 4f 3a 48 4b ab 06 c3
ca_certificate_issuer: Federal Common Policy CA
ca_certificate_subject: Betrusted Production SSP CA A1

**Comment by ryancdickson** [comment]
Will close issue upon revocation event.

As of 2/21/19, certificate still appears valid.
