### ISSUE TITLE
System Notification for: STRAC to FBCA2016 CA Issuance

### ISSUE THREAD

**Issue by weirdscience** [GSA/fpki-guides#416]
notice_date: February 21, 2019
change_type:  CA Certificate Issuance
start_datetime: February 20, 2019
end_datetime: February 19, 2022
system: STRAC Bridge Root Certification Authority
change_description: New cross-certificate issued from STRAC Bridge Root Certification Authority to Federal Bridge 2016
contact: pki at strac dot org
ca_certificate_hash: EE02BDB684AB4714C5F25300C41C5B8F328B0CD9
ca_certificate_issuer: C=US, O=STRAC, OU=STRAC PKI Trust Infrastructure, CN=STRAC Bridge Root Certification Authority
ca_certificate_subject: C=US, O=STRAC, OU=STRAC PKI Trust Infrastructure, CN=STRAC Bridge Root Certification Authority
cdp_uri: http://pki.strac.org/bridge/crl/STRACBridgeRootCA.crl
aia_uri: http://pki.strac.org/bridge/certificates/STRACBridgeRootCA.p7c
sia_uri: http://http.fpki.gov/bridge/caCertsIssuedByfbca2016.p7c
ocsp_uri: http://certstatus.strac.org

**Comment by ryancdickson** [comment]
@weirdscience - I'm working on an update now - would you like me to add this?

**Comment by weirdscience** [comment]
Yes please.

Kenneth Myers
Senior Manager
Protiviti Government Services
+1.571.366.6120 Desk
1640 King Street | Suite #400 | Alexandria | VA 22314 US | ProtivitiGovernmentServices.com
________________________________
