### ISSUE TITLE
System Notification for: DigiCert Shared Service Provider

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#439]
We need to add this from DigiCert teams: https://knowledge.digicert.com/generalinformation/digicert-symantec-managed-pki-data-center-migration-information-.html

notice_date: February 11, 2019
change_type:  URI Change (IP addresses)
start_datetime: April 6, 2019
end_datetime: April 7, 2019
system: 
change_description: 
contact: 
ca_certificate_hash: 
ca_certificate_issuer: 
ca_certificate_subject: 
cdp_uri: 
aia_uri: 
sia_uri: 
ocsp_uri:

**Comment by ryancdickson** [comment]
@lachellel - I'll create the announcement this morning.

**Comment by ryancdickson** [comment]
Published to site. Closing issue.
