### ISSUE TITLE
Navigation Item - Certificate Authorities Page

### ISSUE THREAD

**Issue by djpackham** [GSA/fpki-guides#44]
#### Description of Issue:

Need to update current Certificate Authorities page to include more information about the FPKI certificate authorities.
#### Details of Issue:
- Links need to be updated as well as additional links should be added.
- Update the page with other relevant information aboutFPKI  CAs
#### References (Docs, Links, Files):
- http://pki.treas.gov/
- FPKI Certificate Policies - https://www.idmanagement.gov/IDM/s/article_content_old?tag=a0Gt0000000SfwS
- https://https.cio.gov/certificates/
- FPKI Approved Providers - https://www.idmanagement.gov/IDM/s/article_content_old?tag=a0Gt0000000XRrC
- FPKI Documents - https://www.idmanagement.gov/IDM/s/article_content_old?tag=a0Gt0000000Sfx1
#### If a New Page or Content is Needed, Expected Outcomes:

A content page that includes basic information about the FPKI Certificate Authorities including links to policies.
#### Link to the Content Page for Contributors:

https://github.com/GSA/fpki-guides/blob/staging/pages/fpki_cas.md

**Comment by lachellel** [comment]
eGov CA is being deprecated - do not include

**Comment by djpackham** [comment]
To do:

- Looks like we go back and forth on "certificate authority" and "certification authority". Should we stick with "certification authority" and change everything to that?
- @lachellel did you mention it would be better to remove the "Intermediate Root CA" certificate from the graphics as that may be confusing? https://github.com/GSA/fpki-guides/blob/staging/pages/fpki_cas.md
- Plain language pass

**Comment by lachellel** [comment]
> did you mention it would be better to remove the "Intermediate Root CA" certificate from the graphics as that may be confusing?

this one: [chain](https://github.com/GSA/fpki-guides/blob/staging/img/fcpca-chainV5.png)

**Comment by weirdscience** [comment]
It should always be Certification Authority.

**Comment by weirdscience** [comment]
Intermediate Root CA is contradictory. Where did it come from? It is normally root CA, subordinate CA, intermediate CA, or issuing CA as used in RFC 5280.

**Comment by lachellel** [comment]
> Intermediate Root CA is contradictory. 

Yeah, that's why the image as-is is confusing.  :+1: 

The image is based on mapping from Common to subordinates, and all our lovely CAs with "Root" in the name (the history of where Common came from).   It is confusing to the audience.

**Comment by clstmbrly** [comment]
@djpackham Do your comments from Sept. 28, 2016, above still need to be addressed?  I didn't mark that in my notes from today.  Thanks!

**Comment by djpackham** [comment]
@weirdscience we were planning on changing everything in fpki-guides to certificate authority as it seems both are acceptable (certification authority or certificate authority) and we leaned more towards certificate authority because we thought it would make more sense to those not familiar with the term. Any convincing reason to not use certificate authority?

**Comment by djpackham** [comment]
@clstmbrly, yes I think the overall comments from Sept. 28, 2016 are addressed and just need to address the other items discussed earlier.

**Comment by clstmbrly** [comment]
Thank you.

**Comment by clstmbrly** [comment]
@lachellel @djpackham In this section, we seem to be alternating between using the term, "Trust Stores" (which is also the Guide title here), and the term "Application Trust Stores."  This is potentially confusing, as well as inconsistent.  Would it be okay to use simply "Trust Stores" as the accepted term throughout?

**Comment by lachellel** [comment]
trust stores is fine. 

if we need to change it later based on comments to change it - it's a grep or sed.  :+1:

**Comment by clstmbrly** [comment]
Thanks!  In the table of most common Trust Stores, the link for Adobe Approved Trust List says:  ...apple.com/..  Looks like a mistake...?

**Comment by clstmbrly** [comment]
@lachellel @djpackham Re:  my previous comment.

**Comment by godadada** [comment]
The original post should be with #45

**Comment by godadada** [comment]
Following segment is from fpki_cas.md file. Please confirm the link is correct one. The link is absolute github url, but outside of ficam perview.

{% include alert-info.html content="A new effort is underway to establish a Federal root and issuing certificate authorities dedicated to Public Trust TLS/SSL device certificates. Follow or contribute to the development of the new Federal certificate policy for this Public Trust effort: https://github.com/uspki/policies" %}

**Comment by weirdscience** [comment]
@djpackham Certification Authority is proper term to use and used by industry and in standards to mean CA. Certificate Authority is not the correct term and may be a misuse similar to calling a CPS a Certificate Practice Statement.

**Comment by grandamp** [comment]
The same thing could be said for "cross certificate" -vs- "cross sign", and "certificate path" -vs- "certificate chain".

**Comment by clstmbrly** [comment]
@djpackham I believe that during recent discussions it was decided we would use "certificate authority" vs. "certification authority."  Both seem widely used.  "Certificate authority" is a more plain-language term.

**Comment by weirdscience** [comment]
Plain language does not mean correct.

**Comment by grandamp** [comment]
I would highly recommend aligning terminology with RFC 5280 when possible: 

https://datatracker.ietf.org/doc/rfc5280

It is a common standard that FPKI and CABForum  claim to adhere to.  This not mean that plain language can't be used to describe function and operation.

**Comment by lachellel** [comment]
I'll be honest - I don't have a strong opinion one way or the other.  It's intended for program managers and engineers working in / with the agencies, so if the audience is okay with one or the other and we're not throwing gobbledygook at them...

Def'n of gobbledygook: 

- https://www.merriam-webster.com/dictionary/gobbledygook

Another definition: 

- _noun: gobbledegook; noun: gobbledygook_
- language that is meaningless or is made unintelligible by excessive use of abstruse technical terms; nonsense.

**Comment by lachellel** [comment]
closed with #101 
updates to be certification authority
