### ISSUE TITLE
System Notification for: FPKIMA - Revoke Verizon SSP CA A2

### ISSUE THREAD

**Issue by weirdscience** [GSA/fpki-guides#452]
notice_date: April 2, 2019
change_type:  CA Certificate Revocation
start_datetime: April 2, 2019
end_datetime: April 2, 2019
system: Federal Common Policy CA
change_description: The Verizon SSP CA A2 was issued a new CA certificate and the old one was revoked.
contact: fpki dash help at gsa dot gov 
ca_certificate_hash:  a9d3a8ac016dba9fa12685bf59dcc39f5dcaf781
ca_certificate_issuer: Federal Common Policy
ca_certificate_subject: Verizon SSP CA A2

**Comment by ryancdickson** [comment]
Included update in notification-update-04152019 (branch), PR #464.
