### ISSUE TITLE
System Notification for: FPKI Management Authority CDN Implementation

### ISSUE THREAD

**Issue by weirdscience** [GSA/fpki-guides#462]
notice_date: April 12, 2019
change_type:  Infrastructure Change
start_datetime: On or around April 22, 2019
system: Federal PKI Trust Infrastructure
change_description: The FPKIMA is implementing a Content Delivery Network for HTTP artifacts of the FBCA, FCPCA, SHA1FRCA, and the soon to be commissioned TLS Root CA. The HTTP artifacts include certificate revocation lists, certificates, and certificate bundles (P7C files). No URLs will change with this migration.
contact: fpki dash help at gsa dot gov

**Comment by ryancdickson** [comment]
Included update in notification-update-04152019 (branch), PR #464.
