### ISSUE TITLE
System Notification for: Department of Homeland Security

### ISSUE THREAD

**Issue by ryancdickson** [GSA/fpki-guides#466]
notice_date: April 20, 2019
change_type: Intent to Perform CA Certificate Issuance
start_datetime: June 29, 2019
system: Department of Homeland Security Certification Authority (DHSCA)
change_description: DHS intends to re-key the DHSCA on 6/29/2019. Certificates will be available following the key update at https://pki.treasury.gov/crl_certs.htm.
contact:  gladys dot garcia at hq dot dhs dot gov
ca_certificate_hash:
ca_certificate_issuer:
ca_certificate_subject: OU = DHS CA4, OU = Certification Authorities, OU = Department of Homeland Security, O = U.S. Government, C = US
cdp_uri:
aia_uri:
sia_uri:
ocsp_uri:

**Comment by lachellel** [comment]
See #495 
DHS intends to re-key the DHSCA on 6/6/2019

**Comment by ryancdickson** [comment]
Re-key successful.

New certificate details:
Validity: June 6, 2019, 7:11 a.m. - June 6, 2029, 7:41 a.m. 
Serial #: 5CCB31CA
SHA1: 58085A64E181573F4FD917C5C021EB1CF344DD5F
SHA256: 1F876321693113EA500050531A755716F196DC05EAD8499E794D341F6CB44515

I'll update the notifications page.
