### ISSUE TITLE
System Notification for: Verizon Non-Federal Issuer CAs

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#473]
Verizon will be decommissioning the following CAs approximately July 2019.  Any valid end entity certificates will be revoked; the CAs will be decommissioned and archived; and then the CA certificate from the Federal Bridge CA will be revoked. 

CA CNs: 
- CN=CT-CSSP-CA-A1
- CN=Trans Sped Mobile QCA
- CN=VZ-SMC-CA-B2

More details on the exact dates will be added / updated in June 2019. 

********************************
notice_date: April 26, 2019
change_type:  CA Certificate Revocation
start_datetime: July 2019
system: 
change_description: 
contact: 
ca_certificate_hash: 
ca_certificate_issuer: 
ca_certificate_subject: 
cdp_uri: 
aia_uri: 
sia_uri: 
ocsp_uri:

**Comment by ryancdickson** [comment]
Update:
- Trans Sped Mobile QCA and VZ-SMC-CA-B2 CA certificates have been revoked.
- I reached out to @weirdscience to learn when the Federal Bridge -> CT-CSSP-CA-A1 certificate will be revoked.

**Comment by ryancdickson** [comment]
Update: Awaiting Verizon's confirmation of Letter of Authorization.

**Comment by ryancdickson** [comment]
Letter of Authorization with intent to revoke cross-certificate from FBCA to the Verizon NFI Root CA has been signed. Will add this into #531.

**Comment by ryancdickson** [comment]
8/5/2019 - Revocations have not yet taken place (Federal Bridge <--> CT-CSSP-CA-A1 ). I'll continue to monitor and will close this issue once revocations are complete.

**Comment by ryancdickson** [comment]
Federal Bridge CA 2016 -> CT-CSSP-CA-A1 has been revoked. Followed-up with Verizon to learn when CT-CSSP-CA-A1 -> Federal Bridge CA 2016 revocation will take place. 

I intend to bundle this update in a PR with a few issuances that took place today (WidePoint, STRAC, and DoD).

**Comment by ryancdickson** [comment]
CT-CSSP-CA-A1 -> Federal Bridge CA 2016 certificate revocation planned for Thursday. Will monitor and follow-up once complete.

**Comment by ryancdickson** [comment]
notice_date: August 08, 2019 
change_type: CA Certificate Revocation
start_datetime: 
system: Verizon NFI
change_description: On August 08, 2019, Verizon NFI revoked the certificate issued from CT-CSSP-CA-A1 to the Federal Bridge CA 2016.
contact: andre dot varacka at verizon dot com
ca_certificate_hash: 73dccf6418522b69a50a96721aeb96441e6ef3c0  
ca_certificate_issuer: CN = CT-CSSP-CA-A1, OU = PKI, OU = Services, O = Cybertrust, C = US 
ca_certificate_subject: CN = Federal Bridge CA 2016, OU = FPKI, O = U.S. Government, C = US
cdp_uri: http://cdp1.com-strong-id.net/CDP/CT-CSSP-CA-A1.cr 
aia_uri: http://aia1.com-strong-id.net/CA/CT-CSSP-CA-A1.p7c 
sia_uri: http://http.fpki.gov/bridge/caCertsIssuedByfbca2016.p7c  
ocsp_uri: http://ocsp1.com-strong-id.net/CT-CSSP-CA-A1 

Will include this in Monday's PR.
