### ISSUE TITLE
Navigation Item - FAQ Page

### ISSUE THREAD

**Issue by djpackham** [GSA/fpki-guides#48]
#### Description of Issue:

Need a list of FAQs most common to the Federal PKI
#### References (Docs, Links, Files):
- FPKI FAQ - https://www.idmanagement.gov/IDM/servlet/fileField?entityId=ka0t0000000TNvDAAW&field=File__Body__s
- HSPD-12 FAQ (PKI) - https://www.idmanagement.gov/IDM/servlet/fileField?entityId=ka0t0000000TNMNAA4&field=File__Body__s
- https://https.cio.gov/certificates/
#### If a New Page or Content is Needed, Expected Outcomes:

A content page that contains FPKI related FAQs as well as links to other topics related to FPKI
#### Link to the Content Page for Contributors:

- https://github.com/GSA/fpki-guides/blob/staging/_faq/index.md

**Comment by Protiviti-JSargent** [comment]
this seems like it would be easier to navigate as a collection of FAQ pages rather than combining all FAQs onto one page.

Should the PIV-I FAQ be included as a sub-page here or remain as its own page?

**Comment by lachellel** [comment]
i think you're right - a FAQ collection and we can clean up the overlaps along the way.

**Comment by djpackham** [comment]
I agree as well. We should probably add content on the main FAQ page first, then I can help get a new collection added for FAQ.

**Comment by djpackham** [comment]
To do:
- add content to main FAQ page
- add in sub-pages for the content in the "references" section above
- determine if we should include FAQ in inital launch?

**Comment by clstmbrly** [comment]
@djpackham Did we determine whether to try and add more FAQs and "references" sub-pages content in initial launch and, if yes, who would write up?  Thank you!

**Comment by djpackham** [comment]
I'd focus on the other issues first and then if you have time, come back and work on the FAQ section. Anyone could work on converting the docs to markdown, but then you'd want to have a SME look over the content to make sure it is accurate and up to date.

- My thoughts for the FAQ section is to have a FAQ landing page/parent page, which has [already been created here](https://github.com/GSA/fpki-guides/blob/staging/_faq/index.md).
- Then create a new page for each of the FAQ docs; basically convert the FAQ docs referenced above, into markdown format.
- I believe Jason created a [PIV-I FAQ](https://github.com/GSA/fpki-guides/blob/staging/_faq/fpki_piv-i_faq.md) that is already in the FAQ directory. I believe it still needed a look over for accuracy and to make sure the information isn't outdated. @lachellel what are you thoughts on [this type of FAQ page](https://github.com/GSA/fpki-guides/blob/staging/_faq/fpki_piv-i_faq.md) where it is a running long page dedicated to the overall topic?

**Comment by lachellel** [comment]
> I believe Jason created a PIV-I FAQ that is already in the FAQ directory

I have a local branch just for this FAQ and have been working on it, to align with the updated PIV-I requirements from Nov 2016 (going through final sign-off).  Please do not duplicate effort.  Low priority for an FAQ.

**Comment by lachellel** [comment]
My thoughts:

**No longer valid**

> FPKI FAQ - https://www.idmanagement.gov/IDM/servlet/fileField?entityId=ka0t0000000TNvDAAW&field=File__Body__s


**No longer valid**

> HSPD-12 FAQ (PKI) - https://www.idmanagement.gov/IDM/servlet/fileField?entityId=ka0t0000000TNMNAA4&field=File__Body__s

**Comment by idmken** [comment]
Documents no longer exists. Create a new issue to generate a FAQ page if needed.
