### ISSUE TITLE
System Notification for: SAFE-BioPharma

### ISSUE THREAD

**Issue by davidsimonetti** [GSA/fpki-guides#482]
notice_date: May 9, 2019
change_type:  Planned Infrastructure Change
start_datetime: July 1, 2019
end_datetime: 
system: SAFE-BioPharma
change_description: Synchronoss has informed SAFE-BioPharma that it will decommission the Zentry Certificate Authority that is currently cross-certified with the SAFE-BioPharma Bridge CA on July 1, 2019.  Synchronoss will perform the following actions on this date:
1)      Revoke all unexpired certificates issued from this CA;
2)      Issue a long-term CRL;
3)      Destroy the CA signing keys;
Synchronoss confirms that a long-term data archive is being implemented in accordance with SAFE-BioPharma archive requirements.
contact: David Simonetti
ca_certificate_hash: 
ca_certificate_issuer: 
ca_certificate_subject: 
CN = Trans Sped SAFE CA III
OU = Individual Subscriber CA
O = Trans Sped SRL
C = RO
cdp_uri: 
aia_uri: http://aia3.com-strong-id.net/CA/TS-SAFE-CA-III.p7c
sia_uri: 
ocsp_uri:

**Comment by lachellel** [comment]
thanks @davidsimonetti  - we'll get this notice published.
