### ISSUE TITLE
PIV-I Certification Process

### ISSUE THREAD

**Issue by djpackham** [GSA/fpki-guides#5]
@dasgituser (Dave Silver) is converting document to a play - https://www.idmanagement.gov/IDM/servlet/fileField?entityId=ka0t0000000TNHNAA4&field=File__Body__s

**Comment by dasgituser** [comment]
This PIV-I playbook provides the background information and activities related to the cross-certification process for prospective PIV-I providers, resulting in inclusion on the  PIV-I cross certification list. It also describes requirements that must be met to maintain cross-certification.

**Comment by idmken** [comment]
Document no longer exists.
