### ISSUE TITLE
Navigation Item - Glossary Page

### ISSUE THREAD

**Issue by djpackham** [GSA/fpki-guides#50]
#### Description of Issue:

A glossary that includes an alphabetical list of terms or words found throughout the FPKI Guides Playbook
#### References (Docs, Links, Files):

http://pki.treas.gov/glossary.htm
#### If a New Page or Content is Needed, Expected Outcomes:

A content page that includes a glossary for FPKI Guide Playbook
#### Link to the Content Page for Contributors:

https://github.com/GSA/fpki-guides/blob/staging/pages/fpki_glossary.md

**Comment by djpackham** [comment]
To be done:
- Sift through to see which glossary items should be removed
- align with FICAM and NIST definitions for clarity across govt.
- Determine if we should include glossary as part of initial launch?

**Comment by Protiviti-JSargent** [comment]
Submitted pull request #107 to convert the glossary page to link to reference docs rather than recreating another glossary

**Comment by weirdscience** [comment]
I think this can be closed. The pull request from @protiviti-jsargent to fix this was closed last month.
