### ISSUE TITLE
System Notification for: Federal Bridge CA 2016

### ISSUE THREAD

**Issue by ryancdickson** [GSA/fpki-guides#530]
FPKIMA shared intent to issue certificates to DoD, TSCP, and WidePoint before August 15.

 notice_date: July 24, 2019
  change_type: Intent to Perform CA Certificate Issuance
  start_datetime:  
  system: FPKI Trust Infrastructure - Federal Bridge 2016
  change_description: The Federal Bridge CA 2016 intends to issue cross-certificates to DoD Interoperability Root CA 2, TSCP SHA256 Bridge CA, and WidePoint NFI Root CA 1. Certificate issuance is expected to take place before August 15, 2019.
  contact: fpki dash help at gsa dot gov
  ca_certificate_hash:  
  ca_certificate_issuer: CN = Federal Bridge CA 2016, OU = FPKI, O = U.S. Government, C = US
  ca_certificate_subject: Three certificates are planned for issuance (1) CN = DoD Interoperability Root CA 2, OU = PKI, OU = DoD, O = U.S. Government, C = US, (2) CN = TSCP SHA256 Bridge CA, OU = CAs, O = TSCP Inc., C = US, and (3) CN = WidePoint NFI Root 1, OU = Certification Authorities, O = WidePoint, C = US
  cdp_uri:
  aia_uri:
  sia_uri:
  ocsp_uri:

**Comment by ryancdickson** [comment]
8/5/2019 - No update.  I'm still monitoring issuance activities included within this issue.

**Comment by ryancdickson** [comment]
The certificates were issued. I'll bundle notifications with Monday's Crawler pull request:
<br>

**Federal Bridge CA 2016 -> TSCP SHA256 Bridge CA** 
- Validity: Aug. 6, 2019, 9:34 a.m. - Aug. 6, 2022, 9:33 a.m. 
- Serial #: 146B82AFCD4C573E5FF7188BF3520FBC0C4BADC1
- SHA1: 874007002A4A2FFF3EDCF90EB41ADCE7C2FB4915
- SHA256: 2A3CDD400C292A3F80BAAD0431008CE8D1F92343C388C1D52AEFF1B22F38382E

<br>

**Federal Bridge CA 2016 -> DoD Interoperability Root CA 2** 
- Validity: Aug. 6, 2019, 10:54 a.m. - Aug. 6, 2022, 10:53 a.m. 
- Serial #: 538FA2BBCB68C4DDE2EB504F44060FF41C96A9D6
- SHA1: 73050D5B629CF6286BE972AFDDFA31D2864B4F35
- SHA256: 82CA09462997E440700C2190B3AEB115107C5C9BDBA2EE330D09FC6537AFE08F

<br>

**Federal Bridge CA 2016 ->WidePoint NFI Root 1**
- Validity: Aug. 6, 2019, 9:58 a.m. - Aug. 6, 2022, 9:57 a.m. 
- Serial #: 7345C2F627BEF049BC46990249C97BE5357E0B11
- SHA1: 92BC06FE6B27CBE4723F309F34681FC57C8166CE
- SHA256: 9C4F279AF0C91B0EE650C2996E550D7CEAA17B8CA81257EF0BE22796A4F5705B

Certificates are available at: http://http.fpki.gov/bridge/caCertsIssuedByfbca2016.p7c

**Comment by weirdscience** [comment]
As part of the WidePoint NFI Root 1 issuance there will also be two revocations for ORC NFI CA 2 and ORC NFI CA 3. ORC NFI CA 2 has been revoked.

notice_date: August 14, 2019
change_type: Intent to Perform CA Certificate Revocation
start_datetime: August 14, 2019
system: FPKI Trust Infrastructure - Federal Bridge 2016
change_description: The Federal Bridge CA 2016 and WidePoint intend to revoke the cross-certificates to and from the Federal Bridge CA 2016 and ORC NFI CA 2
contact: fpki dash help at gsa dot gov
ca_certificate_hash: B055C6EE104E01EB688C8FB4F87CF77CA376AFDB
ca_certificate_issuer: CN = Federal Bridge CA 2016, OU = FPKI, O = U.S. Government, C = US
ca_certificate_subject: CN = ORC NFI CA 2, OU = ORC PKI, C = US

**Comment by ryancdickson** [comment]
Published to production site. Closing issue.
