### ISSUE TITLE
System Notification for: Federal Common Policy (Entrust SSP)

### ISSUE THREAD

**Issue by weirdscience** [GSA/fpki-guides#538]
The Federal Common Policy CA intends to issue a modified certificate to the Entrust Managed Services Root CA to support its key rollover.

notice_date: August 14, 2019
change_type: Intent to Perform CA Certificate Issuance
start_datetime: August 14, 2019
system: FPKI Trust Infrastructure - Federal Common Policy CA
change_description: The Federal Common Policy CA intends to issue a certificate to the Entrust Managed Services Root CA.
contact: fpki dash help at gsa dot gov
ca_certificate_hash:
ca_certificate_issuer: CN = Federal Common Policy CA, OU = FPKI, O = U.S. Government, C = US
ca_certificate_subject: OU = Entrust Managed Services Root CA, OU = Certification Authorities, O = Entrust, C = US
cdp_uri: http://http.fpki.gov/fcpca/fcpca.crl
aia_uri: http://http.fpki.gov/fcpca/caCertsIssuedTofcpca.p7c
sia_uri: http://rootweb.managed.entrust.com/SIA/CertsIssuedByEMSRootCA.p7c

**Comment by ryancdickson** [comment]
@weirdscience - I've got the following in the 20190812-auto-fpki-graph-update branch:

- notice_date: August 07, 2019
  change_type: Intent to Perform CA Certificate Issuance
  start_datetime:  
  system: FPKI Trust Infrastructure - Federal Common Policy CA
  change_description: The Federal Common Policy CA intends to issue a certificate to the Entrust Managed Services Root CA, pending the Entrust Managed Services Root CA re-key.
  contact: fpki dash help at gsa dot gov
  ca_certificate_hash:  
  ca_certificate_issuer: CN = Federal Common Policy CA, OU = FPKI, O = U.S. Government, C = US
  ca_certificate_subject: ou=Entrust Managed Services Root CA, ou=Certification Authorities, o=Entrust, c=US
  cdp_uri:
  aia_uri:
  sia_uri:
  ocsp_uri: 

I just closed an open PR for the branch and will now add in the ORC revocation + the issuance notification for the Federal Common Policy CA -> Entrust Managed Services Root.

I'll close this issue, but if you feel it should remain open - please let me know!

**Comment by weirdscience** [comment]
Roger that. I missed it sorry. Entrust certificate has been issued:

ca_certificate_hash: a09655170c87d0fbfe0328b99a7baf4a1cf0b5d9
