### ISSUE TITLE
When Can Announcements Be Removed?

### ISSUE THREAD

**Issue by weirdscience** [GSA/fpki-guides#545]
#### Description of Issue: ####
Announcements are used to inform the community of changes to the FPKI or PKI in general. They have  lifetime when they are no longer relevant.

#### Details of Issue: ####
What is the lifetime and what happens when they are no longer relevant?

#### If a New Page or Content is Needed, Expected Outcomes: ####
Create a new page or directory of archived announcements and number announcements.

#### Link to the Content Page for Contributors: ####
https://fpki.idmanagement.gov/announcements/

**Comment by lachellel** [comment]
Agree!

- I think each announcement will need a timeframe assigned.
- The same for an archival - we will want to remove from the archives too.    

Where do you think the archive should be in the navigation?

**Comment by ryancdickson** [comment]
We could add an item to the announcements collection called "Archived Announcements".  If we name the .md file properly, we can ensure it'll always be the last left-nav sub-menu item under "Announcements".

Once a user navigates to the "Archived Announcements" page they'd see a table presenting a summary of the archived announcements, with a link to the original content (which would no longer be listed on the left nav).

**Comment by sarahdobson** [comment]
You can view a preview on the archive-announcement-demo branch:

https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/gsa/fpki-guides/archive-announcement-demo/announcements/archive/

**Comment by lachellel** [comment]
@sarahdobson lgtm

**Comment by weirdscience** [comment]
Thank you.

Ken Myers
