### ISSUE TITLE
System Notification for: GSA ACES - ORC ACES CA Decommissioning and Revocation

### ISSUE THREAD

**Issue by weirdscience** [GSA/fpki-guides#548]
notice_date: September 3, 2019
change_type:  CA Certificate Revocation
end_datetime: September 3, 2019
system: GSA ACES and Federal Bridge
change_description: WidePoint has decommissioned the ORC ACES 4 CA and the FPKIMA will also revoke the certificate issued from the Federal Bridge CA
contact: fpki dash help at gsa dot gov
ca_certificate_hash: 5573FCC5E6FFFF2B710181ACCAA2EFDADB8F0F4E
ca_certificate_issuer:  C=US, O=U.S. Government, OU=FPKI, CN=Federal Bridge CA 2016
ca_certificate_subject: C=US, O=ORC PKI, CN=ORC ACES 4

**Comment by ryancdickson** [comment]
Thanks, Ken. 

I'll add this to the notifications file during Monday's Crawler update/pull request.

**Comment by weirdscience** [comment]
Certificate has been revoked.

**Comment by ryancdickson** [comment]
Adding to weekly update. Thanks, @weirdscience!

**Comment by ryancdickson** [comment]
Added to System Notifications page. Closing issue.
