### ISSUE TITLE
Intro page configuration?

### ISSUE THREAD

**Issue by djpackham** [GSA/fpki-guides#55]
#### Description of Issue: ####
Currently the index.html in the root directory of FPKI Guides has an include pointing to _includes/index.md. Should we use this for the intro content instead of /pages/fpki_intro.md? Otherwise, should we copy the way the intro page is setup in PIV-Guides?

#### Details of Issue: ####
Currently, there are 2 intro pages, the /index.html is being served first, then the /pages/fpki_intro.md page is served when a user clicks on the Introduction side menu link.

**Comment by lachellel** [comment]
@djpackham 

the _includes/index.md is an old set of files...when i was demo'ing and reusing repos for different purposes...before we cleaned up some of the piv-guides... 

I would use piv-guides model for consistency for now?

**Comment by djpackham** [comment]
@lachellel 

Sound good. Thanks :)

**Comment by djpackham** [comment]
Resolved
