### ISSUE TITLE
System Notification for: Federal PKI Trust Infrastructure - New Federal Bridge CA

### ISSUE THREAD

**Issue by weirdscience** [GSA/fpki-guides#558]
notice_date: September 30, 2019
change_type:  New CA
system: Federal Bridge CA
change_description: Intent to commission a new Federal Bridge CA around the end of October and re-issue existing CA certificates from the Federal Bridge 2016.
contact: fpki dash help at GSA dot gov

**Comment by ryancdickson** [comment]
@weirdscience - Is it possible the name will change from "Federal Bridge CA 2019" to something else, or is that name safe to use in the notification?

**Comment by weirdscience** [comment]
I think we are going with Federal Bridge CA G2.

**Comment by ryancdickson** [comment]
Thanks, @weirdscience. Could you please let me know once the name has been finalized and I'll ensure the notifications are updated correctly?

**Comment by weirdscience** [comment]
Federal Bridge CA G4

**Comment by ryancdickson** [comment]
Notice added to FPKI-Guides.
