### ISSUE TITLE
System Notification for: Federal Bridge CA

### ISSUE THREAD

**Issue by weirdscience** [GSA/fpki-guides#573]
notice_date: October 28, 2019
change_type:  CA Certificate Issuance
start_datetime: October 28, 2019
end_datetime: October 28, 2020
system: Federal Bridge CA 2016
change_description: One year cross-certificates issuance to the Federal Common Policy CA.
contact: fpki dash help at gsa dot gov
ca_certificate_hash: 38341412caa3d72ade61022240411444d21b1de9
ca_certificate_issuer: Federal Bridge CA 2016
ca_certificate_subject: Federal Common Policy CA
cdp_uri: http://http.fpki.gov/bridge/fbca2016.crl
aia_uri: http://http.fpki.gov/bridge/caCertsIssuedTofbca2016.p7c
sia_uri: http://http.fpki.gov/fcpca/caCertsIssuedByfcpca.p7c

**Comment by lachellel** [comment]
closed #580
