### ISSUE TITLE
System Notification for: Federal Common Policy CA

### ISSUE THREAD

**Issue by weirdscience** [GSA/fpki-guides#574]
notice_date: October 28, 2019
change_type:  CA Certificate Issuance
start_datetime: October 28, 2019
end_datetime: October 28, 2020
system: Federal Common Policy CA
change_description: One year certificate issuance to the Federal Bridge CA 2016
contact: fpki dash help at gsa dot gov
ca_certificate_hash: bd38b7e253cfc5dd278a927f88833fb44c6af03a
ca_certificate_issuer: Federal Common Policy CA
ca_certificate_subject: Federal Bridge CA 2016
cdp_uri: http://http.fpki.gov/fcpca/fcpca.crl
aia_uri: http://http.fpki.gov/fcpca/caCertsIssuedTofcpca.p7c
sia_uri: http://http.fpki.gov/bridge/caCertsIssuedByfbca2016.p7c

**Comment by lachellel** [comment]
close #580
