### ISSUE TITLE
System Notification for: SHA-1 Federal Root CA

### ISSUE THREAD

**Issue by weirdscience** [GSA/fpki-guides#577]
notice_date: November 4, 2019
change_type:  CA Decommission
system: Federal PKI Management Authority - SHA-1 Federal Root CA
change_description: Intent to decommission the SHA-1 Federal Root CA in December 2019. Let subordinate certificates to/From CertiPath Bridge and DoD Interoperability Root CA 1 expire on Nov 15th and Nov 29th.
contact: fpki dash help at gsa dot gov
ca_certificate_hash: 27C589FF2853BD1949CFA433F36A5E285B2E2C7C
ca_certificate_issuer: C=US, O=U.S. Government, OU=FPKI, CN=Federal Common Policy CA
ca_certificate_subject: C=US, O=U.S. Government, OU=FPKI, CN=SHA-1 Federal Root CA G2

**Comment by ryancdickson** [comment]
CA Decommissioned. Notice added to FPKI-Guides.
