### ISSUE TITLE
System Notification for: USPTO

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#589]
Placeholder notification issue for the new USPTO cross cert.  

notice_date: 
change_type:  CA Certificate Issuance
start_datetime: 
end_datetime: 
system: 
change_description: 
contact: 
ca_certificate_hash: 
ca_certificate_issuer: 
ca_certificate_subject: 
cdp_uri: 
aia_uri: 
sia_uri: 
ocsp_uri:

**Comment by ryancdickson** [comment]
Certificate Issued:

notice_date: December 16, 2019
change_type: CA Certificate Issuance
start_datetime:
end_datetime:
system: FPKI Trust Infrastructure - Federal Bridge CA G4
change_description: The Federal Bridge CA G4 issued a cross certificate to the United States Patent and Trademark Office's USPTO_INTR_CA1.
contact: fpki dash help at gsa dot gov
ca_certificate_hash: 978ec2f323452f8f46932b8550663d68b6e96af7
ca_certificate_issuer: CN=Federal Bridge CA G4, OU=FPKI, O=U.S. Government, C=US
ca_certificate_subject: CN=USPTO_INTR_CA1, CN=AIA, CN=Public Key Services, CN=Services, CN=Configuration, DC=uspto, DC=gov
cdp_uri: http://repo.fpki.gov/bridge/fbcag4.crl
aia_uri: http://repo.fpki.gov/bridge/caCertsIssuedTofbcag4.p7c
sia_uri: http://ipki.uspto.gov/IPKI/Certs/IPKICACerts.p7c
ocsp_uri:

I'll add this to this morning's pull request.
