### ISSUE TITLE
Styles for alerts

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#59]
#### Description of Issue: ####
Indicators have been added to highlight key pieces of information - I like it

#### Details of Issue: ####
Should we align the format with icons and colors from US Web Design Standards?

#### References (Docs, Links, Files): ####
https://standards.usa.gov/alerts/

Thoughts?  If so, and you want to update - I can also pull the styles / merge with the ficam-arch style updates; then we can push packages to each repo en masse

@djpackham

**Comment by djpackham** [comment]
@lachellel 

Yes, good call. Using the US Web Design Standards makes sense to me.

I'll update the alert include files and styling to match standards.usa.gov/alerts and submit a PR.

**Comment by lachellel** [comment]
@djpackham 

for the open PRs, let's close/merge/update where needed so i can merge the style updates

I'll submit a PR for the style updates by the 29th

**Comment by djpackham** [comment]
@lachellel 

Merged over the PRs; plan to continue updating and tweaking once styling is merged.

**Comment by lachellel** [comment]
#61 
closing issue
