### ISSUE TITLE
System Notification for: Federal Bridge CA G4 + Federal Common Policy CA (consolidated issue)

### ISSUE THREAD

**Issue by ryancdickson** [GSA/fpki-guides#594]
**Note**: This message consolidates the following planned activities for the Federal Bridge CA G4 and the Federal Common Policy CA into a single issue (in attempt to prevent spamming those watching the project).
1. Federal Bridge CA G4 -> Federal Common Policy CA
1. Federal Bridge CA G4 -> USPTO_INTR_CA1
1. Federal Bridge CA G4 -> CertiPath Bridge CA G2
1. Federal Bridge CA 2016 revocation of ORC NFI CA 3
1. Federal Common Policy CA -> U.S. Department of State AD Root CA
1.  Federal Bridge CA G4 -> Exostar Federated Identity Service Root CA 2
1.  Federal Bridge CA G4 -> [Migration of all remaining CAs certified by Federal Bridge CA 2016]

--------------------------------------------------------------------------------------------------

- notice_date: December 5, 2019
  change_type: Intent to Perform CA Certificate Issuance
  start_datetime:  
  system: FPKI Trust Infrastructure - Federal Bridge CA G4
  change_description: The planned Federal Bridge CA G4 intends to issue a cross certificate to the Federal Common Policy CA.
  contact: fpki dash help at gsa dot gov
  ca_certificate_hash:  
  ca_certificate_issuer: CN=Federal Bridge CA G4, OU=FPKI, O=U.S. Government, C=US
  ca_certificate_subject: CN=Federal Common Policy CA, OU=FPKI, O=U.S. Government, C=US
  cdp_uri:  
  aia_uri:
  sia_uri:  
  ocsp_uri:   
  
- notice_date: December 5, 2019
  change_type: Intent to Perform CA Certificate Issuance
  start_datetime:  
  system: FPKI Trust Infrastructure - Federal Bridge CA G4
  change_description: The planned Federal Bridge CA G4 intends to issue a cross certificate to the United States Patent and Trademark Office's USPTO_INTR_CA1. The new certificate issued to USPTO_INTR_CA1 will replace the existing certificate issued by the Federal Bridge CA 2016 (expires Dec. 15, 2019)
  contact: fpki dash help at gsa dot gov
  ca_certificate_hash:  
  ca_certificate_issuer: CN=Federal Bridge CA G4, OU=FPKI, O=U.S. Government, C=US
  ca_certificate_subject: CN=USPTO_INTR_CA1, CN=AIA, CN=Public Key Services, CN=Services, CN=Configuration, DC=uspto, DC=gov
  cdp_uri:  
  aia_uri:
  sia_uri:  
  ocsp_uri:  
  
- notice_date: December 5, 2019
  change_type: Intent to Perform CA Certificate Issuance
  start_datetime:  
  system: FPKI Trust Infrastructure - Federal Bridge CA G4
  change_description: The planned Federal Bridge CA G4 intends to issue a cross certificate to the CertiPath Bridge CA - G2. The new certificate will replace the existing certificate issued by the Federal Bridge CA 2016 (expires Dec. 15, 2019)
  contact: fpki dash help at gsa dot gov
  ca_certificate_hash:  
  ca_certificate_issuer: CN=Federal Bridge CA G4, OU=FPKI, O=U.S. Government, C=US
  ca_certificate_subject: CN=CertiPath Bridge CA - G2, OU=Certification Authorities, O=CertiPath LLC, C=US
  cdp_uri:  
  aia_uri:
  sia_uri:  
  ocsp_uri:  

- notice_date: December 9, 2019
  change_type: Intent to Perform CA Certificate Revocation
  start_datetime:
  system: FPKI Trust Infrastructure - Federal Bridge CA 2016
  change_description: The Federal PKI Management Authority intends to revoke the certificate issued by the Federal Bridge CA 2016 to ORC NFI CA 3 (operated by WidePoint).	
  contact: fpki at gsa dot gov
  ca_certificate_hash: b625da07302016d2837023bab94b6e0d76fc2e45
  ca_certificate_issuer: CN=Federal Bridge CA 2016, OU=FPKI, O=U.S. Government, C=US
  ca_certificate_subject: CN=ORC NFI CA 3, O=ORC PKI, C=US
  cdp_uri: http://http.fpki.gov/bridge/fbca2016.crl
  aia_uri: http://http.fpki.gov/bridge/caCertsIssuedTofbca2016.p7c
  sia_uri: http://crl-server.orc.com/caCerts/ORCNFI3_SIA.p7c 
  ocsp_uri:  

- notice_date: December 9, 2019
  change_type: Intent to Perform CA Certificate Issuance
  start_datetime:  
  system: FPKI Trust Infrastructure - Federal Common Policy CA
  change_description: The Federal Common Policy CA intends to issue a certificate to the U.S. Department of State AD Root CA. The new certificate will replace the existing certificate (expires on January 27, 2020). 
  contact: fpki dash help at gsa dot gov
  ca_certificate_hash:  
  ca_certificate_issuer: CN=Federal Common Policy CA, OU=FPKI, O=U.S. Government, C=US
  ca_certificate_subject: CN=U.S. Department of State AD Root CA, CN=AIA, CN=Public Key Services, CN=Services, CN=Configuration, DC=state, DC=sbu
  cdp_uri:  
  aia_uri:
  sia_uri:  
  ocsp_uri:
  
- notice_date: December 9, 2019
  change_type: Intent to Perform CA Certificate Issuance
  start_datetime:  
  system: FPKI Trust Infrastructure - Federal Bridge CA G4
  change_description: The planned Federal Bridge CA G4 intends to issue a cross certificate to the Exostar Federated Identity Service Root CA 2. The new certificate will replace the existing certificate issued by the Federal Bridge CA 2016 (expires April 30, 2020).
  contact: fpki dash help at gsa dot gov
  ca_certificate_hash:  
  ca_certificate_issuer: 
  ca_certificate_subject: 
  cdp_uri:  
  aia_uri:
  sia_uri:  
  ocsp_uri:  

- notice_date: December 9, 2019
  change_type: Intent to Perform CA Certificate Issuance
  start_datetime:  
  system: FPKI Trust Infrastructure - Federal Bridge CA G4
  change_description: The Federal PKI Management Authority intends to migrate CAs currently cross-certified by the Federal Bridge CA 2016 to the planned Federal Bridge CA G4. Certificate expiration dates will be the same as those in the valid certificates issued by the Federal Bridge CA 2016.  Once all CA certificates have migrated, all active certificates issued by the Federal Bridge CA 2016 will be revoked and the Federal Bridge CA 2016 will be decommissioned (estimated to take place in March 2020).
  contact: fpki dash help at gsa dot gov
  ca_certificate_hash:  
  ca_certificate_issuer: CN=Federal Bridge CA G4, OU=FPKI, O=U.S. Government, C=US
  ca_certificate_subject: Comma-separated list of the eleven (11) CA Subject Names planned for issuance - 1. OU=GPO PCA, OU=Certification Authorities, OU=Government Printing Office, O=U.S. Government, C=US, 2. CN=Symantec Class 3 SSP Intermediate CA - G3, OU=Symantec Trust Network, O=Symantec Corporation, C=US, 3. OU=Entrust Managed Services NFI Root CA, OU=Certification Authorities, O=Entrust, C=US, 4. CN=SAFE Bridge CA 02, OU=Certification Authorities, O=SAFE-Biopharma, C=US, 5. CN=IdenTrust ACES CA 2, OU=IdenTrust Public Sector, O=IdenTrust, C=US, 6. CN=IdenTrust Global Common Root CA 1, O=IdenTrust, C=US, 7. CN=STRAC Bridge Root Certification Authority, OU=STRAC PKI Trust Infrastructure, O=STRAC, C=US, 8. CN=DigiCert Federated ID L3 CA, OU=www.digicert.com, O=DigiCert Inc, C=US, 9. CN=TSCP SHA256 Bridge CA, OU=CAs, O=TSCP Inc., C=US, 10. CN=WidePoint NFI Root 1, OU=Certification Authorities, O=WidePoint, C=US, 11. CN=DoD Interoperability Root CA 2, OU=PKI, OU=DoD, O=U.S. Government, C=US
  cdp_uri:  
  aia_uri:
  sia_uri:  
  ocsp_uri:

**Comment by lachellel** [comment]
All eleven have been issued.  The notifications needs to be posted (policy requires 2 weeks notice).

**Comment by ryancdickson** [comment]
Updating issue to indicate status of activities: 

- [x] Federal Bridge CA G4 -> Federal Common Policy CA (issued, notification published). 
- [x] Federal Bridge CA G4 -> USPTO_INTR_CA1 (issued, notification published). 
- [x] Federal Bridge CA G4 -> CertiPath Bridge CA G2 (issued, notification published). 
- [ ] Federal Bridge CA 2016 revocation of ORC NFI CA 3 (activity pending)
- [x] Federal Common Policy CA -> U.S. Department of State AD Root CA (issued, notification published). 
- [x] Federal Bridge CA G4 -> Exostar Federated Identity Service Root CA 2 (activity TBD)
- [x] Federal Bridge CA G4 -> [Migration of all remaining CAs certified by Federal Bridge CA 2016]
  **Note**: *All certificates migrated except CN=WidePoint NFI Root 1, OU=Certification Authorities, O=WidePoint, C=US. WidePoint may be standing up a new Root and in turn may not migrate the existing CA to be signed by Federal Bridge CA G4.*

**Comment by ryancdickson** [comment]
Update: Confirmed WidePoint will stand up WidePoint NFI Root 2. WidePoint NFI Root 1 will be retired and will not be issued a cross certificate from Federal Bridge CA G4. See #626.

**Comment by ryancdickson** [comment]
Updates: 
- February 14, 2020: **Exostar** submitted a Certificate Request Form to have the Federal Bridge CA G4 issue a 3-year cross certificate to the Exostar Federated Identity Service Root CA 2.
     - The "Intent to Perform CA Certificate Issuance" System Notification was published on December 9, 2019. 
     - This issue will be updated upon certificate issuance.

**Comment by ryancdickson** [comment]
Update: The Federal Bridge CA G4 -> Exostar Federated Identity Service Root CA 2 cross certificate has been issued.

- notice_date: March 4, 2020
  change_type: CA Certificate Issuance
  system: FPKI Trust Infrastructure - Federal Bridge CA G4
  change_description: The Federal Bridge CA G4 issued a cross certificate to Exostar Federated Identity Service Root CA 2.
  contact: fpki dash help at gsa dot gov
  ca_certificate_hash: 3930a7c9ce718d0994394feea49a4ada1ebf665d 
  ca_certificate_issuer: CN=Federal Bridge CA G4, OU=FPKI, O=U.S. Government, C=US
  ca_certificate_subject: CN=Exostar Federated Identity Service Root CA 2, OU=Certification Authorities, O=Exostar LLC, C=US 
  cdp_uri: http://repo.fpki.gov/bridge/fbcag4.crl
  aia_uri: http://repo.fpki.gov/bridge/caCertsIssuedTofbcag4.p7c
  sia_uri: http://www.fis.evincible.com/fis/public/ExostarFederatedIdentityServiceRootCA2.p7c
  ocsp_uri: 

I'll now close this issue because the Federal Bridge CA 2016 revocation of ORC NFI CA 3 is being tracked in #626.
