### ISSUE TITLE
Removing SHA-1 

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#602]
#### Description of Issue: ####
Remove SHA-1
https://github.com/GSA/fpki-guides/blob/staging/pages/fpki_cas.md

#### Details of Issue: ####
Remove SHA-1

#### References (Docs, Links, Files): ####
https://github.com/GSA/fpki-guides/blob/staging/pages/fpki_cas.md

@grandamp @ryancdickson @maxwellfunk  Would anyone like to do the honors?  We could also send a virtual "Happy SHA-1 CA deprecation!" card out and thank all the teams.

**Comment by maxwellfunk** [comment]
I think we will also need to update the CA/CRLs page: https://fpki.idmanagement.gov/crls/... plan to draft some changes on 12/30.

**Comment by lachellel** [comment]
Good catch - i pushed another commit to this PR: 
 #606
