### ISSUE TITLE
Notification Updates For Recent FBCA G4 Issuances

### ISSUE THREAD

**Issue by maxwellfunk** [GSA/fpki-guides#604]
Consolidating in previous fork regarding issue 599 (DigiCert -> Dept of Education Device CA), new branch.

- notice_date: December 23, 2019
  change_type: CA Certificate Issuance
  start_datetime: December 16, 2019
  end_datetime: February 28, 2022
  system: FPKI Trust Infrastructure - Federal Bridge CA G4
  change_description: The Federal Bridge CA G4 issued a cross certificate to the DigiCert Federated ID L3 CA. 
  contact: fpki dash help at gsa dot gov
  ca_certificate_hash: 28f059e2dffac9de78fb7a1670c082dad2522d3b
  ca_certificate_issuer: CN=Federal Bridge CA G4, OU=FPKI, O=U.S. Government, C=US
  ca_certificate_subject: CN=DigiCert Federated ID L3 CA, OU=www.digicert.com, O=DigiCert Inc, C=US.
  cdp_uri:  http://repo.fpki.gov/bridge/fbcag4.crl
  aia_uri:  http://repo.fpki.gov/bridge/caCertsIssuedTofbcag4.p7c
  sia_uri:
  ocsp_uri:  
  
- notice_date: December 23, 2019
  change_type: CA Certificate Issuance
  start_datetime: December 16, 2019
  end_datetime: August 6, 2022
  system: FPKI Trust Infrastructure - Federal Bridge CA G4
  change_description: The Federal Bridge CA G4 issued a cross certificate to the DoD Interoperability Root CA 2. 
  contact: fpki dash help at gsa dot gov
  ca_certificate_hash: ad9f51f8030956e9b85423256911868fd7a370cb
  ca_certificate_issuer: CN=Federal Bridge CA G4, OU=FPKI, O=U.S. Government, C=US
  ca_certificate_subject: CN=DoD Interoperability Root CA 2, OU=PKI, OU=DoD, O=U.S. Government, C=US.
  cdp_uri:  http://repo.fpki.gov/bridge/fbcag4.crl
  aia_uri:  http://repo.fpki.gov/bridge/caCertsIssuedTofbcag4.p7c
  sia_uri:
  ocsp_uri:  
  
- notice_date: December 23, 2019
  change_type: CA Certificate Issuance
  start_datetime: December 16, 2019
  end_datetime: November 16, 2020
  system: FPKI Trust Infrastructure - Federal Bridge CA G4
  change_description: The Federal Bridge CA G4 issued a cross certificate to the Entrust Managed Services NFI Root CA. 
  contact: fpki dash help at gsa dot gov
  ca_certificate_hash: 313f87f0eb4f8e6c658f5e66f58764282c54fba4
  ca_certificate_issuer: CN=Federal Bridge CA G4, OU=FPKI, O=U.S. Government, C=US
  ca_certificate_subject: OU=Entrust Managed Services NFI Root CA, OU=Certification Authorities, O=Entrust, C=US.
  cdp_uri:  http://repo.fpki.gov/bridge/fbcag4.crl
  aia_uri:  http://repo.fpki.gov/bridge/caCertsIssuedTofbcag4.p7c
  sia_uri:  http://nfirootweb.managed.entrust.com/SIA/CAcertsIssuedByNFIRootCA.p7c
  ocsp_uri:  
  
- notice_date: December 23, 2019
  change_type: CA Certificate Issuance
  start_datetime: December 16, 2019
  end_datetime: August 3, 2020
  system: FPKI Trust Infrastructure - Federal Bridge CA G4
  change_description: The Federal Bridge CA G4 issued a cross certificate to the GPO PCA. 
  contact: fpki dash help at gsa dot gov
  ca_certificate_hash: de8171556288add44e16d631653c46adab4dcf79
  ca_certificate_issuer: CN=Federal Bridge CA G4, OU=FPKI, O=U.S. Government, C=US
  ca_certificate_subject: OU=GPO PCA, OU=Certification Authorities, OU=Government Printing Office, O=U.S. Government, C=US.
  cdp_uri:  http://repo.fpki.gov/bridge/fbcag4.crl
  aia_uri:  http://repo.fpki.gov/bridge/caCertsIssuedTofbcag4.p7c
  sia_uri:  http://www.gpo-fbca-crls.ois.gpo.gov/caCertsIssuedByGPO.p7c
  ocsp_uri:  
  
  
- notice_date: December 23, 2019
  change_type: CA Certificate Issuance
  start_datetime: December 17, 2019
  end_datetime: August 21, 2021
  system: FPKI Trust Infrastructure - Federal Bridge CA G4
  change_description: The Federal Bridge CA G4 issued a cross certificate to the IdenTrust ACES CA 2. 
  contact: fpki dash help at gsa dot gov
  ca_certificate_hash: 1e5a60b592dfdbeea3d99a5225abc5e2239b987e
  ca_certificate_issuer: CN=Federal Bridge CA G4, OU=FPKI, O=U.S. Government, C=US
  ca_certificate_subject: CN=IdenTrust ACES CA 2, OU=IdenTrust Public Sector, O=IdenTrust, C = US.
  cdp_uri:  http://repo.fpki.gov/bridge/fbcag4.crl
  aia_uri:  http://repo.fpki.gov/bridge/caCertsIssuedTofbcag4.p7c
  sia_uri:  http://validation.identrust.com/certs/issuedbyacesca2.p7c
  ocsp_uri:  
  
- notice_date: December 23, 2019
  change_type: CA Certificate Issuance
  start_datetime: December 17, 2019
  end_datetime: August 21, 2021
  system: FPKI Trust Infrastructure - Federal Bridge CA G4
  change_description: The Federal Bridge CA G4 issued a cross certificate to the IdenTrust Global Common Root CA 1. 
  contact: fpki dash help at gsa dot gov
  ca_certificate_hash: 2800ea6ecdeb8efc1cf4c042d712e8622e0cbb1a
  ca_certificate_issuer: CN=Federal Bridge CA G4, OU=FPKI, O=U.S. Government, C=US
  ca_certificate_subject: CN=IdenTrust Global Common Root CA 1, O=IdenTrust, C=US.
  cdp_uri:  http://repo.fpki.gov/bridge/fbcag4.crl
  aia_uri:  http://repo.fpki.gov/bridge/caCertsIssuedTofbcag4.p7c
  sia_uri:  http://validation.identrust.com/roots/IssuedbyIGCRootCA1.p7c
  ocsp_uri:  
  
- notice_date: December 23, 2019
  change_type: CA Certificate Issuance
  start_datetime: December 17, 2019
  end_datetime: June 7, 2021
  system: FPKI Trust Infrastructure - Federal Bridge CA G4
  change_description: The Federal Bridge CA G4 issued a cross certificate to the SAFE Bridge CA 02. 
  contact: fpki dash help at gsa dot gov
  ca_certificate_hash: 600319e6c322229f88e0f434ba96fb0dfd00252e
  ca_certificate_issuer: CN=Federal Bridge CA G4, OU=FPKI, O=U.S. Government, C=US
  ca_certificate_subject: CN=SAFE Bridge CA 02, OU=Certification Authorities, O=SAFE-Biopharma, C=US.
  cdp_uri:  http://repo.fpki.gov/bridge/fbcag4.crl
  aia_uri:  http://repo.fpki.gov/bridge/caCertsIssuedTofbcag4.p7c
  sia_uri:  http://sbca2.safe-biopharma.org/sbca/issuedbySBCA02.p7c
  ocsp_uri:  
  
- notice_date: December 23, 2019
  change_type: CA Certificate Issuance
  start_datetime: December 18, 2019
  end_datetime: August 6, 2022
  system: FPKI Trust Infrastructure - Federal Bridge CA G4
  change_description: The Federal Bridge CA G4 issued a cross certificate to the TSCP SHA256 Bridge CA. 
  contact: fpki dash help at gsa dot gov
  ca_certificate_hash: db3f9cceb6c6be4c03e0997070d09e7e0e7ee38a
  ca_certificate_issuer: CN=Federal Bridge CA G4, OU=FPKI, O=U.S. Government, C=US
  ca_certificate_subject: CN=TSCP SHA256 Bridge CA, OU=CAs, O=TSCP Inc., C=US.
  cdp_uri:  http://repo.fpki.gov/bridge/fbcag4.crl
  aia_uri:  http://repo.fpki.gov/bridge/caCertsIssuedTofbcag4.p7c
  sia_uri:  http://tscp-sia.symauth.com/IssuedBy-tscpbcasha256.p7c
  ocsp_uri:

**Comment by lachellel** [comment]
@maxwellfunk 
Two more still outstanding before closing this issue?  Or should we close and open a new issue?

**Comment by maxwellfunk** [comment]
Not sure which two it would be.  Ryan had generated issuance notifications for PTO and CertiPath earlier last week in the announcements (see below).  Those two were issued on 12/12.

Notice Date: December 16, 2019
System: FPKI Trust Infrastructure - Federal Bridge CA G4
Type: CA Certificate Issuance
Change Description: The Federal Bridge CA G4 issued a cross certificate to the United States Patent and Trademark Office's USPTO_INTR_CA1.
Contact: fpki dash help at gsa dot gov
Certificate Issuer: CN=Federal Bridge CA G4, OU=FPKI, O=U.S. Government, C=US
Certificate Subject: CN=USPTO_INTR_CA1, CN=AIA, CN=Public Key Services, CN=Services, CN=Configuration, DC=uspto, DC=gov
Certificate SHA1 Hash: 978ec2f323452f8f46932b8550663d68b6e96af7
Certificate Revocation List: http://repo.fpki.gov/bridge/fbcag4.crl
Certificate Bundle (AIA): http://repo.fpki.gov/bridge/caCertsIssuedTofbcag4.p7c
Certificate Bundle (SIA): http://ipki.uspto.gov/IPKI/Certs/IPKICACerts.p7c

Notice Date: December 16, 2019
System: FPKI Trust Infrastructure - Federal Bridge CA G4
Type: CA Certificate Issuance
Change Description: The Federal Bridge CA G4 issued a cross certificate to the CertiPath Bridge CA - G2.
Contact: fpki dash help at gsa dot gov
Certificate Issuer: CN=Federal Bridge CA G4, OU=FPKI, O=U.S. Government, C=US
Certificate Subject: CN=CertiPath Bridge CA - G2, OU=Certification Authorities, O=CertiPath LLC, C=US
Certificate SHA1 Hash: 3bfc4df881682f8846bff486d422025aee7494d8
Certificate Revocation List: http://repo.fpki.gov/bridge/fbcag4.crl
Certificate Bundle (AIA): http://repo.fpki.gov/bridge/caCertsIssuedTofbcag4.p7c
Certificate Bundle (SIA): http://certipath-sia.symauth.com/IssuedBy-CertiPathBridgeCA-G2.p7c

**Comment by ryancdickson** [comment]
We can add four (4) more notifications:

<br>

**Federal Bridge CA G4 -> STRAC Bridge Root CA**
- notice_date: January 2, 2020
  change_type: CA Certificate Issuance
  start_datetime: December 17, 2019 
  end_datetime: February 14, 2022 
  system: FPKI Trust Infrastructure - Federal Bridge CA G4
  change_description: The Federal Bridge CA G4 issued a cross certificate to the STRAC Bridge Root Certification Authority.
  contact: fpki dash help at gsa dot gov
  ca_certificate_hash: c6d4d588000e823cfaf2ecf551ebcd3827fd71b6 
  ca_certificate_issuer: CN=Federal Bridge CA G4, OU=FPKI, O=U.S. Government, C=US
  ca_certificate_subject: CN=STRAC Bridge Root Certification Authority,OU=STRAC PKI Trust Infrastructure,O=STRAC,C=US
  cdp_uri: http://repo.fpki.gov/bridge/fbcag4.crl  
  aia_uri: http://repo.fpki.gov/bridge/caCertsIssuedTofbcag4.p7c  
  sia_uri: http://pki.strac.org/bridge/certificates/STRACBridgeRootCA.p7c
  ocsp_uri:  

<br>

**Federal Bridge CA G4 -> Symantec Class 3 SSP Intermediate - G3**
- notice_date: January 2, 2020
  change_type: CA Certificate Issuance
  start_datetime: December 18, 2019 
  end_datetime:  October 25, 2020
  system: FPKI Trust Infrastructure - Federal Bridge CA G4
  change_description: The Federal Bridge CA G4 issued a cross certificate to Symantec Class 3 SSP Intermediate CA - G3.  
  contact: fpki dash help at gsa dot gov
  ca_certificate_hash: a99a0d6510b59b6dc92270eae1f24fbc21d2dcce 
  ca_certificate_issuer: CN=Federal Bridge CA G4, OU=FPKI, O=U.S. Government, C=US
  ca_certificate_subject: CN=Symantec Class 3 SSP Intermediate CA - G3,OU=Symantec Trust Network,O=Symantec Corporation,C=US
  cdp_uri: http://repo.fpki.gov/bridge/fbcag4.crl  
  aia_uri: http://repo.fpki.gov/bridge/caCertsIssuedTofbcag4.p7c  
  sia_uri: http://ssp-sia.symauth.com/STNSSP/Certs_Issued_by_Class3SSPCA-G3.p7
  ocsp_uri:  

<br>

**Federal Common Policy CA -> State AD Root CA**
- notice_date: January 2, 2020
  change_type: CA Certificate Issuance
  start_datetime: December 18, 2019 
  end_datetime: December 18, 2022 
  system: FPKI Trust Infrastructure - Federal Common Policy CA
  change_description: The Federal Common Policy CA issued a cross certificate to the U.S. Department of State AD Root CA. 
  contact: fpki dash help at gsa dot gov
  ca_certificate_hash: ce11590010562a39ad8b1455acf76c03737aebf6 
  ca_certificate_issuer: CN=Federal Common Policy CA, OU=FPKI, O=U.S. Government, C=US
  ca_certificate_subject: CN=U.S. Department of State AD Root CA,CN=AIA,CN=Public Key Services,CN=Services,CN=Configuration,DC=state,DC=sbu
  cdp_uri: http://http.fpki.gov/fcpca/fcpca.crl  
  aia_uri: http://http.fpki.gov/fcpca/caCertsIssuedTofcpca.p7c   
  sia_uri: http://crls.pki.state.gov/SIA/CertsIssuedByADRootCA.p7c
  ocsp_uri:    
  
<br>

**SHA-1 Deprecation**  
- notice_date: January 2, 2020
  change_type: CA Certificate Expiration
  start_datetime: January 9, 2017 
  end_datetime: December 31, 2019
  system: FPKI Trust Infrastructure
  change_description: The certificate issued by the Federal Common Policy CA to SHA-1 Federal Root CA G2 expired on December 31, 2019. The expiration of this certificate marks the deprecation of SHA-1 certificates in the Federal PKI.
  contact: fpki dash help at gsa dot gov
  ca_certificate_hash: 27c589ff2853bd1949cfa433f36a5e285b2e2c7c 
  ca_certificate_issuer: CN=Federal Common Policy CA, OU=FPKI, O=U.S. Government, C=US
  ca_certificate_subject: CN=SHA-1 Federal Root CA G2, OU = FPKI, O = U.S. Government, C = US
  cdp_uri: http://http.fpki.gov/fcpca/fcpca.crl  
  aia_uri: http://http.fpki.gov/fcpca/caCertsIssuedTofcpca.p7c  
  sia_uri: http://http.fpki.gov/sha1frca/caCertsIssuedBysha1frcaG2.p7c
  ocsp_uri:    
    

I'll add to a new branch and submit a pull request.

**Comment by lachellel** [comment]
Let's remove the enddate from all of these?  

We should probably remove enddate entirely from the notifications or clarify it's intent.  The original intent wasn't "the end date of a certificate" but rather "the end date of a system outage or change window".

**Comment by ryancdickson** [comment]
I can do that! We don't display end date on the notifications page, but de-cluttering is good.

**Comment by ryancdickson** [comment]
Pull Request Merged. Closing issue.
