### ISSUE TITLE
System Notification for: TSCP SHA256 Bridge CA (to Fortior Solutions)

### ISSUE THREAD

**Issue by ryancdickson** [GSA/fpki-guides#617]
notice_date: January 7, 2020
change_type: Intent to Perform CA Certificate Issuance
start_datetime:
system: TSCP SHA256 Bridge CA
change_description: The Transglobal Secure Collaboration Program (TSCP) SHA256 Bridge CA intends to issue a cross certificate to Fortior Solutions. This is a renewal for the cross certificate from the TSCP SHA256 Bridge CA to Fortior Solutions Intermediate CA 2018, expiring February 11, 2020.
contact: steve.race at tscp dot org
ca_certificate_hash:
ca_certificate_issuer: CN=TSCP SHA256 Bridge CA, OU=CAs, O=TSCP Inc., C=US
ca_certificate_subject: CN=Fortior Solutions Intermediate CA 2018, OU=Certificate Authorities, O=Fortior Solutions, C=US
cdp_uri:
aia_uri:
sia_uri:
ocsp_uri:

**Comment by lachellel** [comment]
closed by #621

**Comment by ryancdickson** [comment]
Certificate Issued:
- Issuer: CN = TSCP SHA256 Bridge CA, OU = CAs, O = TSCP Inc., C = US 
- Subject: CN = Fortior Solutions Intermediate CA 2018, OU = Certificate Authorities, O = Fortior Solutions, C = US
- Validity: January 22, 2020 to January 22, 2021 
- Serial #: 3cd4087a04abd3ed749d9c3cb6ad7cf9 
- SHA-1 Hash: 000ea5b4b63f39d083bd5a0777ca334d6ff58c94 
- Note: This is a certificate renewal. Authority Key Information and Subject Key Information are identical to the existing cross certificate (Serial #27b8a4d10d26c56e4438b8c393610ef9, SHA-1 Hash: aebdf407b44afd431d8364012e096aea2a32a55d) which expires in February.
