### ISSUE TITLE
System Notification for: TSCP SHA256 Bridge CA (to Alexion Pharmaceuticals, Inc.)

### ISSUE THREAD

**Issue by ryancdickson** [GSA/fpki-guides#618]
notice_date: January 7, 2020
change_type: Intent to Perform CA Certificate Issuance
start_datetime:
system: TSCP SHA256 Bridge CA
change_description: The Transglobal Secure Collaboration Program (TSCP) SHA256 Bridge CA intends to issue a cross certificate to Alexion Pharmaceuticals, Inc. This is a renewal for the cross certificate from the TSCP SHA256 Bridge CA to the Alexion Pharmaceuticals Issue 2 CA, expiring January 23, 2020.
contact: steve.race at tscp dot org
ca_certificate_hash:
ca_certificate_issuer: CN=TSCP SHA256 Bridge CA, OU=CAs, O=TSCP Inc., C=US
ca_certificate_subject: CN=Alexion Pharmaceuticals Issue 2 CA, OU=CAs, O=Alexion, Pharmaceuticals, C=US
cdp_uri:
aia_uri:
sia_uri:
ocsp_uri:

**Comment by lachellel** [comment]
closed by #621

**Comment by ryancdickson** [comment]
Certificate issued:
- Issuer: CN = TSCP SHA256 Bridge CA, OU = CAs, O = TSCP Inc., C = US 
- Subject: CN = Alexion Pharmaceuticals Issue 2 CA, OU = CAs, O = Alexion Pharmaceuticals, C = US
- Validity: January 22, 2020 to January 22, 2021 
- Serial #: 477bb79a8d56c62d2f7edbd31bc8f895  
- SHA-1 Hash: 2d7b753e7aee8a31ccf77fc6b1f6ff48a15debba  
- Note: This is a renewal and replaces the now expired cross-certificate with serial # 0c35e25346e6287d2092eb05c0d53c31 and SHA-1 hash 692a53fa725e5581a5b1db1c3d7b27e6feb9cae8.
