### ISSUE TITLE
System Notification: Widepoint NFI Root CA 2

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#626]
Initial placeholder info: 

notice_date: January 18, 2020
change_type: CA Certificate Issuance
start_datetime: 
system:  Federal Bridge CA G4
change_description: 
contact: fpki at gsa dot gov
ca_certificate_hash: 
ca_certificate_issuer: 
ca_certificate_subject: cn=WidePoint NFI Root 2, ou=Certification Authorities, o=WidePoint, c=US 
cdp_uri: 
aia_uri: 
sia_uri: 
ocsp_uri:

**Comment by ryancdickson** [comment]
Thanks for posting, @lachellel (still working my way through my inbox).

Additional activities referenced:
- WidePoint NFI Root CA 2 will issue a certificate to ORC NFI 3 
- WidePoint will retire WidePoint NFI Root CA 1 (active certificates issued by WidePoint NFI Root CA 1 will first be revoked)
- WidePoint will request revocation of the certificate issued by Federal Bridge CA 2016 to WidePoint NFI Root CA 1
- Two-way cross certificates issued to/from Federal Bridge CA 2016 and  ORC NFI CA 3 will be revoked. 

I'll monitor moving forward (and prepare necessary System Notifications).

**Comment by jsalga01** [comment]
Ryan,

 

Please let us know when WidePoint will perform these activities. Thanks.

 

John

**Comment by ryancdickson** [comment]
Update: 
- Federal Bridge CA G4 issued the cross certificate to WidePoint NFI Root 2.

Pending activities:
- WidePoint NFI Root CA 2 -> ORC NFI 3
- Federal Bridge CA 2016 revocation of cross certificate to WidePoint NFI Root CA 1 
- WidePoint NFI Root CA 1 Retirement
- Federal Bridge CA 2016 revocation of cross certificate to ORC NFI CA 3
- ORC NFI CA 3 revocation of cross certificate to Federal Bridge CA 2016

**Comment by ryancdickson** [comment]
Update:
- WidePoint NFI Root CA 2 issued a certificate to ORC NFI 3

Pending activities:
- Federal Bridge CA 2016 revocation of cross certificate to WidePoint NFI Root CA 1
- WidePoint NFI Root CA 1 Retirement
- Federal Bridge CA 2016 revocation of cross certificate to ORC NFI CA 3
- ORC NFI CA 3 revocation of cross certificate to Federal Bridge CA 2016

**Comment by ryancdickson** [comment]
Updates:
- Federal Bridge CA 2016 revoked the cross certificate issued to WidePoint NFI Root 1
- Federal Bridge CA 2016 revoked the cross certificate issued to ORC NFI CA 3
- ORC NFI CA 3 revoked the cross certificate issued to Federal Bridge CA 2016
