### ISSUE TITLE
System Notification for: Department of State (re-key of U.S. Department of State PIV CA2)

### ISSUE THREAD

**Issue by ryancdickson** [GSA/fpki-guides#627]
notice_date: January 23, 2020
change_type: Intent to Perform CA Certificate Issuance
start_datetime:
system: U.S. Department of State AD Root CA
change_description: The Department of State intends to re-key U.S. Department of State PIV CA2. The CA signing key length will be changed from its current 2048-bit key size to 3072-bits.
contact: shomolp at state.gov or shanleyrj at state dot gov
ca_certificate_hash:
ca_certificate_issuer: CN = U.S. Department of State AD Root CA, CN = AIA, CN = Public Key, Services, CN = Services, CN = Configuration, DC = state, DC = sbu
ca_certificate_subject: OU = U.S. Department of State PIV CA2, OU = Certification Authorities, OU = PIV, OU = Department of State, O = U.S. Government, C = US
cdp_uri:
aia_uri:
sia_uri:
ocsp_uri:

**Comment by jsalga01** [comment]
Ryan,

 

Is there an estimated date for re-key? Thanks.

 

John

**Comment by ryancdickson** [comment]
@jsalga01 - We were notified the activity is planned for 1/24/2020.

**Comment by ryancdickson** [comment]
Certificate issued. 

- Issuer: CN = U.S. Department of State AD Root CA, CN = AIA, CN = Public Key Services, CN = Services, CN = Configuration, DC = state, DC = sbu
- Subject: OU = U.S. Department of State PIV CA2, OU = Certification Authorities, OU = PIV, OU = Department of State, O = U.S. Government, C = US
- Serial #: 51b0b97f
- Validity: January 24, 2020 to January 24, 2030
- Thumbprint: 68a4e9ab7a1fb8fb85316a770ff9ca874c020724

Will add to today's pull request.
