### ISSUE TITLE
Playbook for client certificate encryption exchange

### ISSUE THREAD

**Issue by djpackham** [GSA/fpki-guides#65]

**Comment by weirdscience** [comment]
Is this FPKI or PIV guide? Might be confusing moving forward. Any end user questions seem like they should be PIV. I'll move this to the PIV Guide.

**Comment by djpackham** [comment]
@lachellel - We have the [Engineer Guides](https://github.com/GSA/fpki-guides/blob/staging/_engineer/index.md) section in fpki-guides for basic certificate use cases (i.e. encrypting emails, digitally signing, etc.).
- Would you prefer these types of issues be placed in piv-guides since they are related to **using** your PIV credential?
- If so, we could aim the FPKI Engineer guides to answer more of the crawler output and generic certificate type of issues?

**Comment by lachellel** [comment]
agree with @djpackham and @weirdscience for minimum viable
while there is more than "piv" obviously, the fpki guides can first focus on the broad engineering challenges as stated.  

- crawler
- information useful for configuring trust stores (finding all the certs for one, which packages from the crawler should be used, is the crawler info still valid)
- info for ocsp responders (local) which is dependent upon having certs packaged and issuer names

**Comment by djpackham** [comment]
Moving to PIV Guides
