### ISSUE TITLE
Announcement:  Federal Common Policy Root CA - 30 day CRLs

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#657]
#### Description of Issue: ####
New announcement 

#### Details of Issue: ####
The FPKIMA will be operating the Federal Common Policy Root CA in an offline operational mode.  Starting March 13, FPKIMA began issuing 30-day CRLs as allowed by the Common Policy CP. 

CRLs will continue to be made available to all relying parties in the same manner as current operations.  The only impact customers will see is the longer expiration date. We do not recommend any change to the frequency with which applications fetch the CRL.  Additionally, any non-emergency certificate activity may need to be postponed due to local travel restrictions. 

FPKIMA personnel will remain available via fpki-help@gsa.gov.

#### If a New Page or Content is Needed, Expected Outcomes: ####
Might need to clarify for different audiences:
>CRLs will continue to be made available to all relying parties in the same manner as current operations.

Cross-reference to CDN announcement or update in this announcement

> Non-emergency certificate activity

this is the CA certificates signed by Common not the end entity certs

**Comment by idmken** [comment]
@ryancdickson is this ready to close?

**Comment by ryancdickson** [comment]
@idmken - seems okay to close, IMO. I believe the original intent was to promote awareness around the change to 30-day CRLs (it was also briefed at FPKIPA meetings).  Given we've been operating this way for almost 9 months, I think the issue has served its purpose.

Feel free to re-open if you disagree.
