### ISSUE TITLE
Explain the difference between trust traversal and encryption certificate discovery

### ISSUE THREAD

**Issue by djpackham** [GSA/fpki-guides#66]

**Comment by weirdscience** [comment]
I can work on this.

**Comment by idmken** [comment]
@maxwellfunk @ryancdickson  I think this came up at an FPKI hackathon day. Is this addressed somewhere or is still relevant. This issue semi-aligns with some content in the FPKI Trust Infrastructure overview, but maybe less specific to FPKI and general how PKI works.

**Comment by ryancdickson** [comment]
@idmken - ironic, I was reviewing this issue prior to submitting this morning's Pull Request.

Considering support emails to our FPKI inboxes, I haven't seen many (if any?) over the past 3 years related to encryption certificate discovery or path discovery/validation (what I assume is "trust traversal").

I agree with your assessment (this is more "PKI 101" than "FPKI-centric").  We do talk a bit about certificate chaining on the homepage, and it's also discussed on PIV-Guides - but this is mostly to serve context that FPKI certificates chain to the Federal Common Policy CA.

For these reasons, I'd probably mark the issue as OBE.
