### ISSUE TITLE
System Notification for: Federal Bridge CA G4 (intent to issue to DigiCert Class 3 SSP Intermediate CA – G4)

### ISSUE THREAD

**Issue by ryancdickson** [GSA/fpki-guides#663]
**Note**: Staging announcement. Letter of Authorization _pending_ approval and signature. 

- notice_date: April 6, 2020
  change_type: Intent to Perform CA Certificate Issuance
  system: FPKI Trust Infrastructure - Federal Bridge CA G4
  change_description: The Federal Bridge CA G4 intends to issue a cross certificate to the new DigiCert Class 3 SSP Intermediate CA – G4. DigiCert plans to migrate CAs signed by the Symantec Class 3 SSP Intermediate CA - G3 to DigiCert Class 3 SSP Intermediate CA – G4.
  contact: fpki dash help at gsa dot gov
  ca_certificate_hash:
  ca_certificate_issuer: CN=Federal Bridge CA G4, OU=FPKI, O=U.S. Government, C=US
  ca_certificate_subject: CN=DigiCert Class 3 SSP Intermediate CA – G4, O=DigiCert, Inc., C=US
  cdp_uri:
  aia_uri:
  sia_uri:
  ocsp_uri:

**Comment by lachellel** [comment]
@ryancdickson was this the CA cert published yesterday?

**Comment by ryancdickson** [comment]
Definitely published between Monday and today (Crawler runs on Mondays, but I could bump this up to daily and only do pull requests on the weekly basis) to catch these things as they happen. 

Will add the following to next week's Crawler execution/Pull request:

notice_date: May 20
change_type: CA Certificate Issuance
system: FPKI Trust Infrastructure - Federal Bridge CA G4
change_description: The Federal Bridge CA G4 issued a cross certificate to the DigiCert Class 3 SSP Intermediate CA – G4. 
contact: fpki dash help at gsa dot gov
ca_certificate_hash: 8a8e06a378289206a64c85ad7dd37846b1ed3aad
ca_certificate_issuer: CN=Federal Bridge CA G4, OU=FPKI, O=U.S. Government, C=US
ca_certificate_subject: CN=DigiCert Class 3 SSP Intermediate CA – G4, O=DigiCert, Inc., C=US
cdp_uri: http://repo.fpki.gov/bridge/fbcag4.cr
aia_uri: http://repo.fpki.gov/bridge/caCertsIssuedTofbcag4.p7c
sia_uri: http://sspsia.digicert.com/STNSSP/Certs_Issued_by_Class3SSPCA-G4.p7c
ocsp_uri:
