### ISSUE TITLE
System Notification for: Federal Bridge CA G4 revocation of GPO (replacement)

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#705]
notice_date: June 26, 2020
change_type:  CA Certificate Revocation 
start_datetime: 
end_datetime: 
system: Federal Bridge CA G4
change_description: The new three year cross-certificate to the Government Publishing Office (GPO) replaces the one expiring on August 3, 2020.  This will revoke the certificate that was set to expire on August 3, 2020. 
contact: fpki dash help at gsa dot gov
ca_certificate_hash: de8171556288add44e16d631653c46adab4dcf79
ca_certificate_issuer: CN=Federal Bridge CA G4, OU=FPKI, O=U.S. Government, C=US
ca_certificate_subject: OU=GPO PCA, OU=Certification Authorities, OU=Government Printing Office, O=U.S. Government, C=US
cdp_uri: http://repo.fpki.gov/bridge/fbcag4.crl
aia_uri: http://repo.fpki.gov/bridge/caCertsIssuedTofbcag4.p7c
sia_uri: http://www.gpo-fbca-crls.ois.gpo.gov/caCertsIssuedByGPO.p7c

**Comment by ryancdickson** [comment]
Confirmation: The certificate was revoked on 7/16/20.
