### ISSUE TITLE
System Notification for: Federal Bridge 2016 revocation of GPO cross-cert

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#706]
notice_date: June 26, 2020
change_type:  CA Certificate Revocation
start_datetime: 
end_datetime: 
system: Federal Bridge CA 2016
change_description: As part of the migration to the Federal Bridge CA G4, the Federal Bridge CA 2016 will revoke the cross certificate issued to GPO PCA Root Certification Authority.
contact: fpki dash help at gsa dot gov
ca_certificate_hash: b8eabb18ed544c9fcfb299bd5d322127e6f48d90
ca_certificate_issuer: CN=Federal Bridge CA 2016, OU=FPKI, O=U.S. Government, C=US
ca_certificate_subject: OU=GPO PCA, OU=Certification Authorities, OU=Government Printing Office, O=U.S. Government, C=US
cdp_uri: http://http.fpki.gov/bridge/fbca2016.crl
aia_uri: http://http.fpki.gov/bridge/caCertsIssuedTofbca2016.p7c
sia_uri: http://www.gpo-fbca-crls.ois.gpo.gov/caCertsIssuedByGPO.p7c
ocsp_uri:

**Comment by ryancdickson** [comment]
Confirmation: The certificate was revoked on July 16, 2020.
