### ISSUE TITLE
System Notification for: Federal Bridge 2016 revocation of SAFE Bridge CA cross-cert

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#707]
notice_date: June 26, 2020
change_type: CA Certificate Revocation
start_datetime:
end_datetime:
system: Federal Bridge CA 2016
change_description: s part of the migration to the Federal Bridge CA G4, the Federal Bridge CA 2016 will revoke the cross certificate issued to SAFE Bridge CA 02 Certification Authority.
contact: fpki dash help at gsa dot gov
ca_certificate_hash: b8eabb18ed544c9fcfb299bd5d322127e6f48d90
ca_certificate_issuer: CN=Federal Bridge CA 2016, OU=FPKI, O=U.S. Government, C=US
ca_certificate_subject: CN=SAFE Bridge CA 02, OU=Certification Authorities, O=SAFE-Biopharma, C=US
cdp_uri: http://http.fpki.gov/bridge/fbca2016.crl
aia_uri: http://http.fpki.gov/bridge/caCertsIssuedTofbca2016.p7c
sia_uri: http://sbca2.safe-biopharma.org/sbca/issuedbySBCA02.p7c

**Comment by ryancdickson** [comment]
Confirmation: The certificate was revoked on July 16, 2020.
