### ISSUE TITLE
Confusion Between FPKI and PIV Guide

### ISSUE THREAD

**Issue by weirdscience** [GSA/fpki-guides#72]
#### Description of Issue: ####
Seems a lot of cross (Similar?) information being presented between the PIV and FPKI Guide.

#### Details of Issue: ####
I was updating the trust store page and @lachellel mentioned there is also a trust store page in the PIV guide. There are questions posted in the FPKI guide which are really end entity type questions that should be in the PIV guide. How to find encryption certificates (iffy) but the only valid method currently is to ask someone to send you a signed email. How to configure apps for client auth.

#### If a New Page or Content is Needed, Expected Outcomes: ####
A reorg of info between the two and be explicit up front.

**Comment by djpackham** [comment]
@weirdscience - agree it is good to make sure we are adding content to the appropriate playbook. The PIV Guides is all about **USING** the PIV credential. Obviously, there are commonalities between a guide all about FPKI and another more PIV specific. I'll close this issue, but moving forward, feel free to keep adding comments if you feel an issue/topic should move to another playbook.
