### ISSUE TITLE
System Notification for: Department of State (intent to issue new CA certificate)

### ISSUE THREAD

**Issue by ryancdickson** [GSA/fpki-guides#721]
The Department of State shared intent to deploy a Derived PIV credential CA.

notice_date: July 14, 2020
change_type: Intent to Perform CA Certificate Issuance
start_datetime:
system: U.S. Department of State AD Root CA
change_description: The Department of State intends to deploy a Derived PIV credential CA.
contact: shanleyrj at state dot gov
ca_certificate_hash: 
ca_certificate_issuer:  CN=U.S. Department of State AD Root CA, CN=AIA, CN=Public Key Services, CN=Services, CN=Configuration, DC=state, DC=sbu
ca_certificate_subject:  CN=U.S. Department of State DPC CA, CN=AIA, CN=Public Key Services, CN=Services, CN=Configuration, DC=state, DC=sbu
cdp_uri:
aia_uri:
sia_uri:
ocsp_uri:

This issue will be updated as the timing of issuance milestones are finalized.

**Comment by idmken** [comment]
@ryancdickson ready to close?

**Comment by ryancdickson** [comment]
@idmken - I typically leave these issues open until certificate issuance and publication (where I'll also add a corresponding System Notification to highlight the actual certificate issuance, rather than the "intent to issue" notice above).  

In this case, the U.S. Department of State DPC CA has not yet been published.

Happy to change the process if you'd prefer otherwise!

**Comment by ryancdickson** [comment]
State has confirmed certificate issuance.

notice_date: January 11, 2021
change_type: CA Certificate Issuance
start_datetime:
system: U.S. Department of State AD Root CA
change_description: The Department of State issued a new CA certificate.
contact: shanleyrj at state dot gov
ca_certificate_hash: a6e9c11ad29fc006ed65b06db32e36a927cb3a48
ca_certificate_issuer: CN=U.S. Department of State AD Root CA, CN=AIA, CN=Public Key Services, CN=Services, CN=Configuration, DC=state, DC=sbu
ca_certificate_subject: CN=U.S.-Department-of-State-DPC-CA, DC=derived, DC= state, DC=sbu
cdp_uri: http://crls.pki.state.gov/crls/DoSADPKIRootCA1.crl
aia_uri: http://crls.pki.state.gov/AIA/CertsIssuedToDoSADRootCA.p7c
sia_uri:
ocsp_uri: http://ocsp.pki.state.gov/OCSP/DoSOCSPResponder

I'll add this into today's Pull Request.

**Comment by ryancdickson** [comment]
Merged into staging. Closing issue.
