### ISSUE TITLE
How to Use and Understand the FPKI Crawler Output

### ISSUE THREAD

**Issue by djpackham** [GSA/fpki-guides#77]

**Comment by weirdscience** [comment]
I can take a stab at this.

**Comment by lachellel** [comment]
TODO: 

- https://github.com/GSA/fpki-guides/blob/staging/pages/fpki_crawler_howto.md

- [ ] update a bit for plain language

- [ ] add into navigation

**Comment by lachellel** [comment]
@djpackham 

Where in the navigation should this go?  Thoughts?

**Comment by djpackham** [comment]
Some possibilities:

- Certificates and CRLs
   - FPKI Crawler

or 

- Useful tools
   - FPKI Crawler

Standalone sidenav item?
- Introduction
- Certification Authorities
- Certificates and CRLs
- Trust Stores
- **FPKI Crawler**

or create a new System Engineer Guides

- System Engineer Guides
   - How to use the FPKI Crawler

**Comment by lachellel** [comment]
I just pushed the framework for this one: 

- Useful tools
  - FPKI Crawler
