### ISSUE TITLE
Editorial Updates from the FPKIMA

### ISSUE THREAD

**Issue by idmken** [GSA/fpki-guides#770]
Editorial and content updates:

Introduction Page: 

- [x] 1. The FPKI CA graphic is out of date (e.g., it shows SHA1 FRCA); it is a small graphic so it may not matter, but if it does, the FPKIMA can provide an update. Note that the dynamic graphic, linked off this page, is up to date.

CA Page: 

- [x] 1. Same as above, the FPKI CA graphic is out of date.
- [x] 2. In 3rd paragraph, we introduce the FPKIMA; recommend making that a clickable link to the FPKIMA page as it is hard to find https://www.idmanagement.gov/community/fpkima/
- [x] 3. In the Public Trust for Websites blue banner describing TLS certificates, last line, there is a GitHub URL that A) is not linked (plaintext) and B) pertains to contributing to development of a policy of which has already been published (version 1.0: https://devicepki.idmanagement.gov/certificatepolicy/).
- [x] 4. Under the Federal Common Policy Certification Authority heading, first sentence, there are two "ands"; "... the FCPCA supports government person trust **and** **and** a small number of agency intranet enterprise"
- [x] 5. The Federal Bridge Certification Authority section is accurate, but will need to be modified soon to remove the language regarding FBCA 2016 (very first sentence and first sentence of last paragraph) once decommissioned. 
- [x] 6. With the ACES decommission scheduled for October 2020, we should probably update the information on this page (two places): 
- [x] - Table at the bottom of the page references ACES. 
- [x] - Banner at the bottom of the page also has information about deprecation of ACES certificates, with a link (not a hyperlink, just plaintext that would have to be copied and pasted) to a document dated 2017 with lots of contact information within that may or may not be outdated.
- [x] - NOTE: The banner also has an email address (GSA-ACES@GSA.gov) that is plaintext; is this email still accurate and if so, from a security perspective, should we obfuscate it (e.g., GSA-ACES[@]GSA.gov or GSA dash ACES at GSA dot gov)?

Trust Stores Page:

- [x] The information banner in the “What are the most commonly used trust stores” reads: The Federal Common Policy CA root certificate will be removed from the Microsoft trust store. It has already been removed from the Apple trust store. Please see the Announcements for more informations and Solutions sections for mitigation actions that you
should take as soon as possible.
- [x] Should we say when it’s going to be removed?
- [x] We reference the Announcements page for more “informations” (spelling error) + that section has not been updated since April 2019
- [x] The last sentence also references a “Solutions” section but there doesn’t appear to be one
- [x] Section title: “What certificate policies are included in COMMON?” This section contains a table of certificate policy OIDs that appear out of date, many don’t match with the latest version of the CP. One example, in the table pertains to the decommissioned SHA 1 FRCA.

Useful Tools Page:

- [x] Certutil’s MSDN link goes to a Microsoft page that was last updated in 2016 and also has a message from Microsoft that they no longer regularly update the page.

Tools -> FPKIAR Page:

- [x] For security purposes, we should follow best practices to prevent email addresses displayed in our web pages from being easily captured by bots. For example, remove any “mail to” option, update distro lists, or obfuscate the addresses. Below are two links on this page:
- [x] FPKIMA help link: mailto:FPKI-help@gsa.gov
- [x] CPWG link: mailto:fpkipa_cpwg@listserve.gsa.gov

Announcements Page:

- [x] The main announcements on this page are dated March or April 2019. These are actually older than some of the items in “Archived Announcements” which date back to October 2019.

System Notifications:

- [x] For security purposes, we should follow best practices to prevent email addresses displayed in our web pages from being easily captured by bots.

Footer:

- [x] See security issue regarding email addresses cited above as it pertains to fpki@gsa.gov

**Comment by lachellel** [comment]
@idmken 

Are these new or the older ones? 

- Example: Item #6 for ACES was removed in #728, and merged to live in #730 
- And for the mail addresses in the "mailto: email address" instances - that is a general requirement for gov pages to have the mailto:.  We discussed these and the very layered spam protections (etc) that are employed outside of web pages.  👍 

The MA - and any team or person - can make these changes and submit a pull request for review and merging too!!

**Comment by idmken** [comment]
Ready to close after #803 merge
