### ISSUE TITLE
Federal Common CA playbook - one minor nit (FAQs)

### ISSUE THREAD

**Issue by lachellel** [GSA/fpki-guides#775]
#### Description of Issue: ####
The FAQ page should have the list of the questions at the top.  
 

#### Details of Issue: ####
Allows the user to quickly see the questions and navigate to their specific question and answer.

#### References (Docs, Links, Files): ####
Add links to top of markdown page - 09_faq.md: 
https://github.com/GSA/fpki-guides/blob/staging/_common/09_faq.md

**Comment by ryancdickson** [comment]
Will do!

**Comment by lachellel** [comment]
@sarahdobson for your review
I think adding the questions to the top of the FAQ page is generally a best practice.  Your advice please (good or bad, mobile, etc).

**Comment by ryancdickson** [comment]
Will be closed with merge of today's pull request.
