### ISSUE TITLE
Navigation: How do readers find the fpki-guides?

### ISSUE THREAD

**Issue by grandamp** [GSA/fpki-guides#88]
#### Description of Issue: ####

How do readers find the fpki-guides?

#### Details of Issue: ####

There does not appear to be a link in the readme.md, or on idmanagement.gov, to the hosted content

**Comment by lachellel** [comment]
thanks @grandamp 

We haven't pushed to a site yet (not even a github pages site).  MVP targeted for 5/1 to launch. 

The navigation bar will be wired into the piv and ficam architecture navigation (refer to the _config.yml) and will be linked from idmanagement.gov

idmanagement.gov is also in migration (in parallel) so everything will start to update and link together soon!

**Comment by lachellel** [comment]
addressed
links are on idmanagement and in the navigation of piv and arch
closing
